[mypy]
python_version = 3.14
warn_return_any = False
warn_unused_ignores = False
ignore_missing_imports = True
check_untyped_defs = False
disallow_untyped_defs = False
exclude = (?x)(
    ^Files/Archivo/
    |^Entrega/
    |^Juego/build/
    )

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-duplicados_lib]
ignore_errors = True

[mypy-utils_puntuacion_materia]
ignore_errors = True

[mypy-utils_plantillas_core]
ignore_errors = True

[mypy-simulacion_evaluacion_azar]
ignore_errors = True

[mypy-equilibrar_pool_extra_juego]
ignore_errors = True

[mypy-cli_examen_historia]
ignore_errors = True

[mypy-validacion_dataset]
ignore_errors = True

[mypy-mantenimiento]
ignore_errors = True

[mypy-motor_partida]
ignore_errors = True

[mypy-modo_feedback]
ignore_errors = True

[mypy-Consola.motor_partida]
ignore_errors = True

[mypy-Consola.modo_feedback]
ignore_errors = True
