sonar.projectKey=Dafafi63f_Escape-Room
sonar.organization=dafafi63f
sonar.projectName=Escape-Room

sonar.sources=Juego,Files/Scripts
sonar.tests=Tests
sonar.python.version=3.10,3.12

sonar.exclusions=**/Archivo/**,**/__pycache__/**,**/build/**,Entrega/**,Revision/**,Data/**
