#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""40 preguntas exclusivas del modo resistencia (1 por materia).

Embebidas en código; no hay fichero JSON externo.
Pool total resistencia = 1000 reales (480 CSV + 480 plantillas + 40 exclusivas).
"""

from __future__ import annotations

from typing import Any

PREGUNTAS_EXCLUSIVAS_RESISTENCIA: tuple[dict[str, Any], ...] = (
    {
        "id": "res_m01",
        "tier": 1,
        "racha_minima": 100,
        "materia": "Àlgebra Lineal",
        "dificultad": "Dificil",
        "tipo": "Calculo",
        "pregunta": "Sea A una matriz 3×3 con traza 0 y determinante 8. ¿Cuál puede ser la suma de sus autovalores reales?",
        "correcta": "B",
        "opciones": {
            "A": "8",
            "B": "0",
            "C": "−8",
            "D": "No están determinados solo por esos datos",
        },
    },
    {
        "id": "res_m02",
        "tier": 1,
        "racha_minima": 100,
        "materia": "Càlcul en una Variable",
        "dificultad": "Dificil",
        "tipo": "Calculo",
        "pregunta": "¿Cuál es el valor de ∫₀^∞ e^(−x²) dx?",
        "correcta": "C",
        "opciones": {
            "A": "1",
            "B": "π",
            "C": "√π/2",
            "D": "π/2",
        },
    },
    {
        "id": "res_m03",
        "tier": 1,
        "racha_minima": 100,
        "materia": "Fonaments de Computadors",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "En la ley de Amdahl, si la fracción paralelizable es p y hay N procesadores ideales, el speedup máximo está acotado por:",
        "correcta": "B",
        "opciones": {
            "A": "N",
            "B": "1/(1−p)",
            "C": "p·N",
            "D": "N²",
        },
    },
    {
        "id": "res_m04",
        "tier": 1,
        "racha_minima": 100,
        "materia": "Iniciació a la Programació",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "Un árbol binario de búsqueda balanceado con n nodos tiene altura en O:",
        "correcta": "B",
        "opciones": {
            "A": "n",
            "B": "log n",
            "C": "n log n",
            "D": "√n",
        },
    },
    {
        "id": "res_m05",
        "tier": 1,
        "racha_minima": 100,
        "materia": "Programari de Sistema",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "Un deadlock requiere típicamente:",
        "correcta": "A",
        "opciones": {
            "A": "Espera circular de recursos",
            "B": "Solo un proceso",
            "C": "Memoria infinita",
            "D": "Ausencia de mutex",
        },
    },
    {
        "id": "res_m06",
        "tier": 1,
        "racha_minima": 100,
        "materia": "Algorítmia i Combinatòria en Grafs. Mètodes Heurístics",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "El algoritmo de Dijkstra requiere típicamente:",
        "correcta": "A",
        "opciones": {
            "A": "Pesos no negativos en aristas",
            "B": "Grafo no dirigido sin pesos",
            "C": "Solo ciclos negativos",
            "D": "Matriz identidad",
        },
    },
    {
        "id": "res_m07",
        "tier": 1,
        "racha_minima": 100,
        "materia": "Càlcul en Diverses Variables",
        "dificultad": "Dificil",
        "tipo": "Calculo",
        "pregunta": "El teorema de Green relaciona una integral de línea con:",
        "correcta": "A",
        "opciones": {
            "A": "Integral doble del rotacional/campo",
            "B": "Solo series de potencias",
            "C": "Determinante 3×3",
            "D": "Entropía de Shannon",
        },
    },
    {
        "id": "res_m08",
        "tier": 1,
        "racha_minima": 100,
        "materia": "Càlcul Numèric",
        "dificultad": "Dificil",
        "tipo": "Calculo",
        "pregunta": "El error de discretización temporal en simulación numérica depende típicamente de:",
        "correcta": "A",
        "opciones": {
            "A": "El paso h y el esquema numérico",
            "B": "Solo del compilador",
            "C": "La marca del monitor",
            "D": "El color del gráfico",
        },
    },
    {
        "id": "res_m09",
        "tier": 1,
        "racha_minima": 100,
        "materia": "Probabilitat",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "Para X~N(μ,σ²), el intervalo μ±1,96σ contiene aproximadamente el:",
        "correcta": "C",
        "opciones": {
            "A": "68% de la masa",
            "B": "90% de la masa",
            "C": "95% de la masa",
            "D": "99% de la masa",
        },
    },
    {
        "id": "res_m10",
        "tier": 1,
        "racha_minima": 100,
        "materia": "Programació Orientada als Objectes",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "El polimorfismo en POO permite:",
        "correcta": "A",
        "opciones": {
            "A": "Tratar objetos de subtipos mediante una interfaz común",
            "B": "Eliminar herencia",
            "C": "Compilar sin clases",
            "D": "Ocultar siempre la implementación",
        },
    },
    {
        "id": "res_m11",
        "tier": 2,
        "racha_minima": 250,
        "materia": "Bases de Dades Relacionals",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "En SQL, una transacción ACID garantiza atomicidad, lo que implica:",
        "correcta": "A",
        "opciones": {
            "A": "Todo o nada en los cambios",
            "B": "Solo lecturas repetibles",
            "C": "Ausencia de índices",
            "D": "Duplicar filas siempre",
        },
    },
    {
        "id": "res_m12",
        "tier": 2,
        "racha_minima": 250,
        "materia": "Equacions Diferencials Ordinàries",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "La solución general de y'=ky (k≠0) es:",
        "correcta": "A",
        "opciones": {
            "A": "Ce^{kx}",
            "B": "Ckx",
            "C": "C/k",
            "D": "Ce^{−kx}",
        },
    },
    {
        "id": "res_m13",
        "tier": 2,
        "racha_minima": 250,
        "materia": "Modelització i Inferència",
        "dificultad": "Dificil",
        "tipo": "Calculo",
        "pregunta": "La varianza muestral sin corregir de [2,4,6] es:",
        "correcta": "A",
        "opciones": {
            "A": "8/3",
            "B": "4",
            "C": "2",
            "D": "8",
        },
    },
    {
        "id": "res_m14",
        "tier": 2,
        "racha_minima": 250,
        "materia": "Tècniques de Disseny d'Algoritmes",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "La programación dinámica resuelve problemas con:",
        "correcta": "A",
        "opciones": {
            "A": "Subestructura óptima y solapamiento de subproblemas",
            "B": "Solo búsqueda exhaustiva",
            "C": "Únicamente grafos bipartitos",
            "D": "Sin memoria auxiliar",
        },
    },
    {
        "id": "res_m15",
        "tier": 2,
        "racha_minima": 250,
        "materia": "Visualització 3D",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "En geometría euclídea, la suma de los ángulos internos de un triángulo es:",
        "correcta": "B",
        "opciones": {
            "A": "Menor que π en todo triángulo",
            "B": "Exactamente π radianes",
            "C": "2π radianes",
            "D": "Depende del área",
        },
    },
    {
        "id": "res_m16",
        "tier": 2,
        "racha_minima": 250,
        "materia": "Anàlisi Complexa i de Fourier",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "Si f es holomorfa en ℂ entero y acotada, por Liouville es:",
        "correcta": "A",
        "opciones": {
            "A": "Constante",
            "B": "Siempre polinomio de grado 10",
            "C": "No analítica",
            "D": "No continua",
        },
    },
    {
        "id": "res_m17",
        "tier": 2,
        "racha_minima": 250,
        "materia": "Anàlisi de Dades Complexes",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "El PageRank mide:",
        "correcta": "A",
        "opciones": {
            "A": "Importancia de nodos por enlaces entrantes",
            "B": "Solo temperatura de CPU",
            "C": "La varianza de una serie",
            "D": "El área bajo una gaussiana",
        },
    },
    {
        "id": "res_m18",
        "tier": 2,
        "racha_minima": 250,
        "materia": "Intel·ligència Artificial",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "La búsqueda A* es óptima con heurística:",
        "correcta": "A",
        "opciones": {
            "A": "Admisible (no sobreestima)",
            "B": "Siempre cero",
            "C": "No consistente nunca",
            "D": "Aleatoria sin límites",
        },
    },
    {
        "id": "res_m19",
        "tier": 2,
        "racha_minima": 250,
        "materia": "Mètodes Numèrics i Probabilístics",
        "dificultad": "Dificil",
        "tipo": "Calculo",
        "pregunta": "El error cuadrático medio de un estimador combina:",
        "correcta": "A",
        "opciones": {
            "A": "Sesgo al cuadrado y varianza",
            "B": "Solo la moda",
            "C": "Únicamente el rango",
            "D": "La entropía del dataset",
        },
    },
    {
        "id": "res_m20",
        "tier": 2,
        "racha_minima": 250,
        "materia": "Optimització",
        "dificultad": "Dificil",
        "tipo": "Calculo",
        "pregunta": "En programación lineal, el método simplex busca:",
        "correcta": "A",
        "opciones": {
            "A": "Vértices factibles del politopo de restricciones",
            "B": "Solo puntos interiores aleatorios",
            "C": "La integral de Fourier",
            "D": "Autovalores de AᵀA",
        },
    },
    {
        "id": "res_m21",
        "tier": 3,
        "racha_minima": 500,
        "materia": "Aprenentatge Computacional",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "El sobreajuste (overfitting) en aprendizaje supervisado ocurre cuando:",
        "correcta": "A",
        "opciones": {
            "A": "El modelo memoriza ruido del entrenamiento",
            "B": "La pérdida de entrenamiento diverge siempre",
            "C": "No hay parámetros ajustables",
            "D": "El dataset es demasiado grande",
        },
    },
    {
        "id": "res_m22",
        "tier": 3,
        "racha_minima": 500,
        "materia": "Computació i Simulació d'Altes Prestacions",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "La ley de Amdahl limita la aceleración por:",
        "correcta": "A",
        "opciones": {
            "A": "La fracción secuencial del programa",
            "B": "El color del cable de red",
            "C": "Solo el tamaño de fuente",
            "D": "La entropía de logs",
        },
    },
    {
        "id": "res_m23",
        "tier": 3,
        "racha_minima": 500,
        "materia": "Equacions en Derivades Parcials",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "La ecuación del calor es parabólica porque:",
        "correcta": "A",
        "opciones": {
            "A": "Modela difusión sin propagación finita de información",
            "B": "Es siempre hiperbólica",
            "C": "No tiene derivadas espaciales",
            "D": "Es solo algebraica",
        },
    },
    {
        "id": "res_m24",
        "tier": 3,
        "racha_minima": 500,
        "materia": "Física, Abstracció i Computació",
        "dificultad": "Dificil",
        "tipo": "Calculo",
        "pregunta": "Un cuerpo de masa m en movimiento circular uniforme de radio r y velocidad v tiene energía cinética:",
        "correcta": "C",
        "opciones": {
            "A": "mvr",
            "B": "mv²/r",
            "C": "½mv²",
            "D": "mω²r",
        },
    },
    {
        "id": "res_m25",
        "tier": 3,
        "racha_minima": 500,
        "materia": "Teoria de la Informació",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "La entropía de Shannon H(X) mide:",
        "correcta": "A",
        "opciones": {
            "A": "Incertidumbre media de una variable aleatoria",
            "B": "Solo la energía del sistema",
            "C": "El rango de una matriz",
            "D": "La latencia de red",
        },
    },
    {
        "id": "res_m26",
        "tier": 3,
        "racha_minima": 500,
        "materia": "Bases de Dades No Relacionals",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "En el teorema CAP, un sistema distribuido no puede garantizar simultáneamente:",
        "correcta": "A",
        "opciones": {
            "A": "Consistencia, disponibilidad y tolerancia a particiones",
            "B": "Solo replicación",
            "C": "Únicamente cifrado",
            "D": "Compilación JIT",
        },
    },
    {
        "id": "res_m27",
        "tier": 3,
        "racha_minima": 500,
        "materia": "Informació Quàntica",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "La medición en base computacional de un qubit colapsa:",
        "correcta": "A",
        "opciones": {
            "A": "La superposición a un resultado 0 o 1",
            "B": "Siempre dos resultados",
            "C": "El qubit a dimensión infinita",
            "D": "La red clásica",
        },
    },
    {
        "id": "res_m28",
        "tier": 3,
        "racha_minima": 500,
        "materia": "Modelització i Simulació",
        "dificultad": "Dificil",
        "tipo": "Calculo",
        "pregunta": "Un paso de Euler explícito para y'=f(t,y) usa:",
        "correcta": "A",
        "opciones": {
            "A": "y_{n+1} = y_n + h f(t_n, y_n)",
            "B": "y_{n+1} = y_n",
            "C": "y_{n+1} = f(t_n, y_n) sin h",
            "D": "y_{n+1} = y_n − h f",
        },
    },
    {
        "id": "res_m29",
        "tier": 3,
        "racha_minima": 500,
        "materia": "Sistemes Distribuïts i el Núvol",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "El teorema de Brewer (CAP) implica que ante partición de red suele sacrificarse:",
        "correcta": "A",
        "opciones": {
            "A": "Consistencia fuerte o disponibilidad",
            "B": "Solo el ancho de banda",
            "C": "Únicamente logs",
            "D": "La compilación",
        },
    },
    {
        "id": "res_m30",
        "tier": 3,
        "racha_minima": 500,
        "materia": "Xarxes Neuronals i Aprenentatge Profund",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "El gradiente desapareciente (vanishing) en redes profundas dificulta:",
        "correcta": "A",
        "opciones": {
            "A": "Entrenar capas iniciales por señal débil hacia atrás",
            "B": "Solo la inferencia",
            "C": "La normalización batch",
            "D": "El uso de GPU",
        },
    },
    {
        "id": "res_m31",
        "tier": 4,
        "racha_minima": 750,
        "materia": "Anàlisi de Dades Financeres",
        "dificultad": "Dificil",
        "tipo": "Calculo",
        "pregunta": "El valor en riesgo (VaR) al 95% estima:",
        "correcta": "A",
        "opciones": {
            "A": "Un cuantil de pérdidas de la cartera",
            "B": "La media de retornos",
            "C": "Solo volatilidad anualizada sin cuantil",
            "D": "El beta del mercado siempre",
        },
    },
    {
        "id": "res_m32",
        "tier": 4,
        "racha_minima": 750,
        "materia": "Anàlisi de Dades Temporals",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "Una serie temporal estacionaria en media tiene:",
        "correcta": "A",
        "opciones": {
            "A": "Media constante en el tiempo",
            "B": "Varianza infinita obligatoria",
            "C": "Tendencia lineal siempre",
            "D": "Solo valores positivos",
        },
    },
    {
        "id": "res_m33",
        "tier": 4,
        "racha_minima": 750,
        "materia": "Anàlisi Topològica de Dades",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "La homología persistente resume:",
        "correcta": "A",
        "opciones": {
            "A": "Nacimiento y muerte de características topológicas al variar escala",
            "B": "Solo medias aritméticas",
            "C": "Autovalores de Markov",
            "D": "Joins SQL",
        },
    },
    {
        "id": "res_m34",
        "tier": 4,
        "racha_minima": 750,
        "materia": "Internet de les Coses",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "MQTT en IoT es un protocolo de mensajería:",
        "correcta": "A",
        "opciones": {
            "A": "Ligero publicar/suscribir",
            "B": "Solo para video 4K",
            "C": "Exclusivo de SQL",
            "D": "De compilación de kernels",
        },
    },
    {
        "id": "res_m35",
        "tier": 4,
        "racha_minima": 750,
        "materia": "Mètodes d Anàlisi en Ciències de la Salut",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "El odds ratio en un estudio de casos y controles compara:",
        "correcta": "A",
        "opciones": {
            "A": "Probabilidades de exposición entre casos y controles",
            "B": "Solo medias de laboratorio",
            "C": "Tamaño de fichero FASTQ",
            "D": "Latencia de HPC",
        },
    },
    {
        "id": "res_m36",
        "tier": 4,
        "racha_minima": 750,
        "materia": "Anàlisi de Dades en Astrofísica",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "La ley de Hubble relaciona distancia galáctica con:",
        "correcta": "A",
        "opciones": {
            "A": "Velocidad de alejamiento",
            "B": "Masa del Sol únicamente",
            "C": "Temperatura del CMB exacta",
            "D": "Spin nuclear",
        },
    },
    {
        "id": "res_m37",
        "tier": 4,
        "racha_minima": 750,
        "materia": "Bioinformàtica",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "BLAST busca secuencias similares mediante:",
        "correcta": "A",
        "opciones": {
            "A": "Heurísticas sobre seeds y extensión local",
            "B": "Ordenación de burbuja de ADN",
            "C": "Solo FFT de imágenes",
            "D": "Cifrado asimétrico",
        },
    },
    {
        "id": "res_m38",
        "tier": 4,
        "racha_minima": 750,
        "materia": "Informació i Seguretat",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "El principio de mínimo privilegio en seguridad implica:",
        "correcta": "A",
        "opciones": {
            "A": "Otorgar solo permisos necesarios",
            "B": "Admin root siempre",
            "C": "Contraseña vacía",
            "D": "Abrir todos los puertos",
        },
    },
    {
        "id": "res_m39",
        "tier": 4,
        "racha_minima": 750,
        "materia": "Teoria de Jocs",
        "dificultad": "Dificil",
        "tipo": "Teoria",
        "pregunta": "El número de aristas de un grafo completo K_n es:",
        "correcta": "C",
        "opciones": {
            "A": "n",
            "B": "n(n−1)",
            "C": "n(n−1)/2",
            "D": "2n",
        },
    },
    {
        "id": "res_m40",
        "tier": 4,
        "racha_minima": 750,
        "materia": "Visió per Computador",
        "dificultad": "Dificil",
        "tipo": "Calculo",
        "pregunta": "RANSAC en estimación robusta de modelos:",
        "correcta": "A",
        "opciones": {
            "A": "Busca consenso ignorando outliers",
            "B": "Elimina todos los inliers",
            "C": "Solo ordena píxeles",
            "D": "Cifra imágenes",
        },
    },
)

