# -*- coding: utf-8 -*-
"""
Catálogo de plantillas estilo internet por temática (currículo CS/matemáticas genérico).
Combina con REPUESTO_CATALOGO mediante fusionar_con_repuesto.
"""

from __future__ import annotations

from pathlib import Path

BASE = Path(__file__).resolve().parent.parent

from plantillas_repuesto_catalogo import REPUESTO_CATALOGO

MATERIA_TEMATICA: dict[str, str] = {
    'Àlgebra Lineal': 'Algebra i Geometria',
    'Càlcul en una Variable': 'Calcul i Equacions',
    'Fonaments de Computadors': 'Sistemes i Seguretat Computacional',
    'Iniciació a la Programació': 'Programacio de Software',
    'Programari de Sistema': 'Algoritmia i Teoria de Jocs',
    'Algorítmia i Combinatòria en Grafs. Mètodes Heurístics': 'Algoritmia i Teoria de Jocs',
    'Càlcul en Diverses Variables': 'Calcul i Equacions',
    'Càlcul Numèric': 'Metodes Numerics i Optimitzacio',
    'Probabilitat': 'Probabilitat i Ciencia de Dades',
    'Programació Orientada als Objectes': 'Programacio de Software',
    'Bases de Dades Relacionals': 'Bases de Dades',
    'Equacions Diferencials Ordinàries': 'Calcul i Equacions',
    'Modelització i Inferència': 'Probabilitat i Ciencia de Dades',
    "Tècniques de Disseny d'Algoritmes": 'Algoritmia i Teoria de Jocs',
    'Visualització 3D': 'Algebra i Geometria',
    'Anàlisi Complexa i de Fourier': 'Calcul i Equacions',
    'Anàlisi de Dades Complexes': 'Probabilitat i Ciencia de Dades',
    'Intel·ligència Artificial': 'Intel·ligencia Artificial i Aprenentatge Automatic',
    'Mètodes Numèrics i Probabilístics': 'Metodes Numerics i Optimitzacio',
    'Optimització': 'Metodes Numerics i Optimitzacio',
    'Aprenentatge Computacional': 'Intel·ligencia Artificial i Aprenentatge Automatic',
    "Computació i Simulació d'Altes Prestacions": 'Metodes Numerics i Optimitzacio',
    'Equacions en Derivades Parcials': 'Calcul i Equacions',
    'Física, Abstracció i Computació': 'Modelitzacio Fisica i Informacio',
    'Teoria de la Informació': 'Modelitzacio Fisica i Informacio',
    'Bases de Dades No Relacionals': 'Bases de Dades',
    'Informació Quàntica': 'Modelitzacio Fisica i Informacio',
    'Modelització i Simulació': 'Modelitzacio Fisica i Informacio',
    'Sistemes Distribuïts i el Núvol': 'Sistemes i Seguretat Computacional',
    'Xarxes Neuronals i Aprenentatge Profund': 'Intel·ligencia Artificial i Aprenentatge Automatic',
    'Anàlisi de Dades Financeres': 'Probabilitat i Ciencia de Dades',
    'Anàlisi de Dades Temporals': 'Probabilitat i Ciencia de Dades',
    'Anàlisi Topològica de Dades': 'Probabilitat i Ciencia de Dades',
    'Internet de les Coses': 'Sistemes i Seguretat Computacional',
    'Mètodes d Anàlisi en Ciències de la Salut': 'Bases de Dades',
    'Anàlisi de Dades en Astrofísica': 'Probabilitat i Ciencia de Dades',
    'Bioinformàtica': 'Probabilitat i Ciencia de Dades',
    'Informació i Seguretat': 'Sistemes i Seguretat Computacional',
    'Teoria de Jocs': 'Algoritmia i Teoria de Jocs',
    'Visió per Computador': 'Intel·ligencia Artificial i Aprenentatge Automatic',
}

BANCO_POR_TEMATICA: dict[str, list[dict]] = {
    'Algebra i Geometria': [
        {'pregunta': '¿Cuál es la dimensión máxima del espacio de soluciones de Ax=0 si A es 3×5 y rango(A)=2?',
         'A': '3',
         'B': '2',
         'C': '5',
         'D': '1',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Calculo'}
,
        {'pregunta': 'Una matriz ortogonal Q cumple típicamente:',
         'A': 'Q^T Q = I',
         'B': 'det(Q)=0',
         'C': 'Q es diagonal siempre',
         'D': 'Q^T = -Q',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'El producto vectorial a×b en R³ es perpendicular a:',
         'A': 'a y b',
         'B': 'solo a',
         'C': 'solo b',
         'D': 'ningún vector',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': '¿Qué implica que v1,...,vn sean linealmente independientes?',
         'A': 'Ningún vi es combinación de los demás',
         'B': 'Todos son ortogonales',
         'C': 'Todos tienen norma 1',
         'D': 'La matriz es simétrica',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'El rango de una matriz m×n verifica:',
         'A': 'rango ≤ min(m,n)',
         'B': 'rango = m+n',
         'C': 'rango = det(A) siempre',
         'D': 'rango ≥ n siempre',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un autovalor λ de A satisface:',
         'A': 'det(A-λI)=0',
         'B': 'tr(A)=λ siempre',
         'C': 'A=λI',
         'D': 'λ es siempre real',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La traza de una matriz cuadrada es:',
         'A': 'suma de elementos diagonales',
         'B': 'producto de autovalores',
         'C': 'número de filas nulas',
         'D': 'norma Frobenius',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un espacio euclídeo de dimensión n tiene base ortonormal de tamaño:',
         'A': 'n',
         'B': 'n+1',
         'C': 'n-1',
         'D': 'infinito',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La proyección de v sobre u (u≠0) es:',
         'A': '((v·u)/(u·u)) u',
         'B': 'v-u',
         'C': 'u×v',
         'D': 'det(v,u)',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Calculo'}
,
        {'pregunta': 'Dos vectores son ortogonales si:',
         'A': 'su producto escalar es cero',
         'B': 'tienen igual norma',
         'C': 'son paralelos',
         'D': 'suman cero',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'El determinante de AB (cuadradas del mismo tamaño) es:',
         'A': 'det(A)det(B)',
         'B': 'det(A)+det(B)',
         'C': 'det(A)-det(B)',
         'D': 'tr(AB)',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Una transformación lineal T: R^n→R^m se representa por matriz de tamaño:',
         'A': 'm×n',
         'B': 'n×m',
         'C': 'n×n siempre',
         'D': '1×1',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La dimensión del espacio imagen de T coincide con:',
         'A': 'rango de su matriz',
         'B': 'dim del kernel siempre',
         'C': 'número de columnas nulas',
         'D': 'traza',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'En R³, el volumen del paralelepípedo definido por a,b,c es |det([a b c])| si:',
         'A': 'las columnas son los vectores',
         'B': 'solo si son unitarios',
         'C': 'nunca',
         'D': 'si a=b',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Calculo'}
,
        {'pregunta': 'Una forma bilineal simétrica definida positiva induce:',
         'A': 'un producto escalar',
         'B': 'solo un vector nulo',
         'C': 'matriz antisimétrica',
         'D': 'grupo no abeliano',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La descomposición SVD de A (m×n) usa matrices:',
         'A': 'U (m×m), Σ (m×n), V^T (n×n)',
         'B': 'solo QR',
         'C': 'solo LU',
         'D': 'identidad',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'El ángulo entre vectores no nulos u y v satisface cos θ =',
         'A': '(u·v)/(||u|| ||v||)',
         'B': 'u×v',
         'C': 'det(u,v)',
         'D': 'u+v',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Calculo'}
,
        {'pregunta': 'Un subespacio de R^n es cerrado bajo:',
         'A': 'suma y producto por escalar',
         'B': 'solo producto punto',
         'C': 'división siempre',
         'D': 'inversión de matrices',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La matriz identidad I_n tiene determinante:',
         'A': '1',
         'B': '0',
         'C': 'n',
         'D': '-1',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Si A es invertible, entonces A^{-1} existe y:',
         'A': 'AA^{-1}=I',
         'B': 'A^T=0',
         'C': 'det(A)=0',
         'D': 'rango=0',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'En coordenadas homogéneas 3D, un punto (x,y,z) se escribe (xw,yw,zw,w) con w≠0 para:',
         'A': 'representar transformaciones afines como productos 4×4',
         'B': 'eliminar perspectiva',
         'C': 'evitar matrices',
         'D': 'integrar ODEs',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Una rotación en R² se modela típicamente con matriz:',
         'A': 'ortogonal de determinante 1',
         'B': 'diagonal arbitraria',
         'C': 'triangular inferior con ceros',
         'D': 'nula',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'El teorema espectral para matrices simétricas reales garantiza:',
         'A': 'autovalores reales y autovectores ortogonales',
         'B': 'todos los autovalores complejos no reales',
         'C': 'A no diagonalizable',
         'D': 'det=0',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
    ],
    'Algoritmia i Teoria de Jocs': [
        {'pregunta': 'La complejidad O(n log n) típica de mergesort es:',
         'A': 'peor caso comparaciones',
         'B': 'O(1) siempre',
         'C': 'O(n^3)',
         'D': 'exponencial siempre',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Dijkstra requiere pesos:',
         'A': 'no negativos',
         'B': 'negativos arbitrarios',
         'C': 'solo cero',
         'D': 'complejos',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un algoritmo greedy es óptimo globalmente solo si:',
         'A': 'hay propiedad de estructura greedy (ej. matroides)',
         'B': 'siempre',
         'C': 'nunca',
         'D': 'solo en grafos completos',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'NP-completo significa:',
         'A': 'NP y tan difícil como cualquier NP',
         'B': 'en P siempre',
         'C': 'decidible en O(1)',
         'D': 'solo enumerable',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Backtracking explora:',
         'A': 'árbol de decisiones con poda',
         'B': 'solo BFS sin memoria',
         'C': 'solo hashing',
         'D': 'solo GPU',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un matching bipartito máximo se resuelve clásicamente con:',
         'A': 'Hopcroft-Karp u otros',
         'B': 'solo ordenación',
         'C': 'solo FFT',
         'D': 'solo RSA',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Programación dinámica evita:',
         'A': 'recomputar subproblemas',
         'B': 'usar memoria',
         'C': 'tablas',
         'D': 'optimalidad',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un heap binario permite extraer mínimo en:',
         'A': 'O(log n)',
         'B': 'O(1) siempre',
         'C': 'O(n^2)',
         'D': 'O(n!)',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Teoría de juegos: estrategia dominante es:',
         'A': 'mejor respuesta independiente de otros',
         'B': 'siempre aleatoria',
         'C': 'siempre colaborativa',
         'D': 'sin pagos',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Equilibrio de Nash en juegos finitos:',
         'A': 'nadie mejora desviándose unilateralmente',
         'B': 'suma cero siempre',
         'C': 'cooperación obligatoria',
         'D': 'sin información',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un árbol B+ en índices BD mantiene:',
         'A': 'datos en hojas enlazadas',
         'B': 'todo en raíz',
         'C': 'sin balance',
         'D': 'solo hash',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Branch and bound usa:',
         'A': 'cotas para podar',
         'B': 'solo fuerza bruta',
         'C': 'solo ML',
         'D': 'solo TLS',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'El problema del viajante (TSP) es:',
         'A': 'NP-difícil clásico',
         'B': 'en P siempre',
         'C': 'O(1)',
         'D': 'decidible lineal',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un flujo máximo en red se calcula con:',
         'A': 'Ford-Fulkerson u variantes',
         'B': 'solo DFS sin capacidades',
         'C': 'solo sorting',
         'D': 'solo FFT',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Heurística 2-opt mejora:',
         'A': 'tours TSP locales',
         'B': 'solo matrices',
         'C': 'solo PDE',
         'D': 'solo TLS',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Coloración de grafos mínima es:',
         'A': 'NP-difícil en general',
         'B': 'siempre 2 colores',
         'C': 'O(1)',
         'D': 'sin aristas',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Union-Find con compresión y rango opera casi en:',
         'A': 'α(n) amortizado',
         'B': 'O(n^3)',
         'C': 'O(1) peor siempre',
         'D': 'exponencial',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'A* usa heurística h admisible si:',
         'A': 'h nunca sobreestima coste a meta',
         'B': 'h es cero siempre',
         'C': 'h aleatoria',
         'D': 'sin grafo',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Minimax en juegos de dos jugadores asume:',
         'A': 'oponente minimiza tu utilidad',
         'B': 'cooperación total',
         'C': 'azar sin árbol',
         'D': 'sin poda',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Poda alfa-beta reduce:',
         'A': 'nodos evaluados en árbol de juego',
         'B': 'memoria a cero',
         'C': 'profundidad a infinito',
         'D': 'tablas hash',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un problema de mochila 0-1 clásico es:',
         'A': 'NP-difícil pseudo-polinomial con DP',
         'B': 'O(1) siempre',
         'C': 'sin pesos',
         'D': 'sin valores',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'PageRank modela importancia con:',
         'A': 'cadena de Markov en grafo web',
         'B': 'solo BFS',
         'C': 'solo FFT',
         'D': 'solo LU',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un algoritmo aleatorizado de Monte Carlo puede:',
         'A': 'dar respuesta correcta con alta probabilidad',
         'B': 'ser siempre exacto determinista',
         'C': 'sin aleatoriedad',
         'D': 'sin entrada',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
    ],
    'Bases de Dades': [
        {'pregunta': 'ACID en transacciones significa:',
         'A': 'Atomicidad, Consistencia, Aislamiento, Durabilidad',
         'B': 'solo API',
         'C': 'solo CSS',
         'D': 'solo FFT',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Normalización 3FN elimina típicamente:',
         'A': 'dependencias transitivas',
         'B': 'todas las tablas',
         'C': 'índices',
         'D': 'SQL',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un índice B-tree acelera:',
         'A': 'búsquedas por clave ordenada',
         'B': 'siempre escrituras',
         'C': 'sin lecturas',
         'D': 'solo full scan',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'JOIN INNER devuelve:',
         'A': 'filas con coincidencia en ambas tablas',
         'B': 'todas sin coincidencia',
         'C': 'solo izquierda sin match',
         'D': 'vacío siempre',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'MVCC en PostgreSQL permite:',
         'A': 'lecturas sin bloquear escritores típicamente',
         'B': 'sin versiones',
         'C': 'solo tabla única',
         'D': 'sin transacciones',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'NoSQL documental almacena:',
         'A': 'documentos JSON/BSON',
         'B': 'solo relaciones 3FN',
         'C': 'solo FFT',
         'D': 'solo TLS',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'CAP en BD distribuida relaciona:',
         'A': 'consistencia, disponibilidad, tolerancia partición',
         'B': 'solo CPU',
         'C': 'solo GPU',
         'D': 'solo ODE',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un deadlock se resuelve a veces con:',
         'A': 'detección y abort de transacción',
         'B': 'ignorar locks',
         'C': 'sin aislamiento',
         'D': 'solo UDP',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Sharding horizontal particiona:',
         'A': 'filas entre nodos',
         'B': 'columnas en un solo nodo siempre',
         'C': 'solo logs',
         'D': 'solo UI',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'MapReduce procesa datos con:',
         'A': 'map y reduce distribuidos',
         'B': 'solo SQL local',
         'C': 'solo TLS',
         'D': 'solo LU',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Una clave foránea garantiza:',
         'A': 'integridad referencial',
         'B': 'sin joins',
         'C': 'sin índices',
         'D': 'sin filas',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'OLAP vs OLTP: OLAP orienta a:',
         'A': 'análisis agregado histórico',
         'B': 'transacciones cortas operativas',
         'C': 'solo MQTT',
         'D': 'solo RSA',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Event sourcing guarda:',
         'A': 'secuencia de eventos de estado',
         'B': 'solo última foto',
         'C': 'sin auditoría',
         'D': 'solo RAM',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Cassandra usa modelo:',
         'A': 'wide-column distribuido',
         'B': 'solo grafo local',
         'C': 'solo relacional estricto',
         'D': 'solo latex',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un plan de consulta cost-based elige:',
         'A': 'orden de joins e índices',
         'B': 'siempre full scan',
         'C': 'sin estadísticas',
         'D': 'solo UI',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Índice hash es ideal para:',
         'A': 'igualdad exacta',
         'B': 'rangos ordenados',
         'C': 'ordenación global',
         'D': 'solo texto completo',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': '2PC en transacciones distribuidas tiene fase:',
         'A': 'prepare y commit',
         'B': 'solo map',
         'C': 'solo reduce',
         'D': 'solo FFT',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Denormalización controlada busca:',
         'A': 'menos joins a costa de redundancia',
         'B': 'eliminar datos',
         'C': 'sin lecturas',
         'D': 'sin escrituras',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Graph DB destaca en:',
         'A': 'consultas de vecindad/relaciones',
         'B': 'solo agregados tabulares masivos',
         'C': 'solo LU',
         'D': 'solo Poisson',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'SQL injection se evita con:',
         'A': 'parámetros preparados',
         'B': 'concatenar input',
         'C': 'sin BD',
         'D': 'solo GET',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Réplica maestro-esclavo sirve para:',
         'A': 'lecturas escaladas y backup',
         'B': 'sin consistencia nunca',
         'C': 'solo GPU',
         'D': 'solo FFT',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un warehouse columnar (Parquet) optimiza:',
         'A': 'lecturas analíticas por columnas',
         'B': 'OLTP row-wise',
         'C': 'solo MQTT',
         'D': 'solo TLS',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Consistencia eventual en NoSQL implica:',
         'A': 'convergencia tardía entre réplicas',
         'B': 'ACID fuerte instantáneo siempre',
         'C': 'sin réplicas',
         'D': 'sin red',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
    ],
    'Calcul i Equacions': [
        {'pregunta': "La regla de L'Hôpital aplica a límites indeterminados del tipo:",
         'A': '0/0 o ∞/∞ bajo hipótesis',
         'B': 'siempre 0·∞ sin condiciones',
         'C': 'solo integrales',
         'D': 'solo series divergentes',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': "Una EDO lineal de primer orden y'+p(x)y=q(x) se resuelve con factor integrante:",
         'A': 'e^{∫p(x)dx}',
         'B': 'e^{y}',
         'C': '1/y',
         'D': 'sin integrales',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Calculo'}
,
        {'pregunta': 'La transformada de Laplace convierte convolución en:',
         'A': 'producto de transformadas',
         'B': 'suma de derivadas',
         'C': 'división de polinomios',
         'D': 'integral impropia siempre cero',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La serie de Taylor de e^x en 0 es:',
         'A': 'Σ x^n/n!',
         'B': 'Σ x^n',
         'C': 'Σ (-1)^n x^n',
         'D': 'Σ x^{2n}/(2n)!',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Una función holomorfa en un dominio simplement conexo admite:',
         'A': 'primitiva compleja',
         'B': 'siempre polos',
         'C': 'no es continua',
         'D': 'serie divergente siempre',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'El método de separación de variables en EDP busca soluciones:',
         'A': 'u(x,t)=X(x)T(t)',
         'B': 'solo constantes',
         'C': 'solo numéricas Monte Carlo',
         'D': 'sin condiciones de frontera',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La integral ∫_0^1 x^2 dx vale:',
         'A': '1/3',
         'B': '1/2',
         'C': '1',
         'D': '2/3',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Calculo'}
,
        {'pregunta': 'Si f es derivable en a, entonces f es:',
         'A': 'continua en a',
         'B': 'siempre acotada en R',
         'C': 'siempre convexa',
         'D': 'periódica',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'El gradiente ∇f apunta hacia:',
         'A': 'máximo crecimiento local de f',
         'B': 'mínimo global siempre',
         'C': 'origen',
         'D': 'vector cero siempre',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La ecuación de ondas u_tt = c² u_xx modeliza:',
         'A': 'vibraciones y ondas',
         'B': 'solo difusión estacionaria',
         'C': 'solo Poisson eléctrica',
         'D': 'flujo incompresible',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Una integral de línea ∫_C F·dr depende de:',
         'A': 'curva y orientación',
         'B': 'solo del punto final',
         'C': 'solo de |F|',
         'D': 'coordenadas polares únicamente',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Calculo'}
,
        {'pregunta': 'El teorema de Green relaciona integral de línea con:',
         'A': 'integral doble sobre región',
         'B': 'serie de Fourier',
         'C': 'autovalores',
         'D': 'determinante',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La convergencia uniforme de fn a f implica:',
         'A': 'intercambio límite-integral bajo hipótesis',
         'B': 'siempre divergencia',
         'C': 'fn no continuas',
         'D': 'no afecta derivadas nunca',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La transformada de Fourier convierte derivada temporal en:',
         'A': 'multiplicación por iω en dominio frecuencia',
         'B': 'logaritmo',
         'C': 'integral doble',
         'D': 'valor en cero',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': "Un sistema lineal x'=Ax tiene solución fundamental:",
         'A': 'e^{At}',
         'B': 'solo diagonal A',
         'C': 'sin autovalores',
         'D': 'solo numérica',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La ecuación de Laplace Δu=0 describe:',
         'A': 'estado estacionario sin fuentes',
         'B': 'onda transportada',
         'C': 'reacción-diffusión',
         'D': 'caos determinista',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'El jacobiano de una aplicación R^n→R^m es matriz de:',
         'A': 'derivadas parciales m×n',
         'B': 'integrales',
         'C': 'autovalores',
         'D': 'segundas derivadas solo',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Una función convexa cumple que su Hessiana es:',
         'A': 'semidefinida positiva (donde existe)',
         'B': 'siempre nula',
         'C': 'indefinida siempre',
         'D': 'ortogonal',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': "El método de Euler explícito para y'=f(t,y) usa:",
         'A': 'y_{n+1}=y_n+h f(t_n,y_n)',
         'B': 'y_{n+1}=y_n',
         'C': 'solo Newton-Raphson',
         'D': 'multigrid',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Calculo'}
,
        {'pregunta': 'La integral impropia ∫_1^∞ 1/x^p converge si:',
         'A': 'p>1',
         'B': 'p<1',
         'C': 'p=1',
         'D': 'p=0',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Calculo'}
,
        {'pregunta': 'El teorema de Stokes generaliza:',
         'A': 'curl y circulación a superficies',
         'B': 'solo álgebra lineal',
         'C': 'solo probabilidad',
         'D': 'cifrado RSA',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Una EDP parabólica típica es la de:',
         'A': 'calor/difusión',
         'B': 'onda hiperbólica',
         'C': 'Laplace elíptica',
         'D': 'Bernoulli',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La fórmula de Cauchy para integrales complejas requiere:',
         'A': 'f holomorfa en disco cerrado',
         'B': 'f discontinua',
         'C': 'dominio no simplemente conexo siempre',
         'D': 'solo valores reales',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
    ],
    'Intel·ligencia Artificial i Aprenentatge Automatic': [
        {'pregunta': 'Overfitting en ML se combate con:',
         'A': 'regularización, más datos, validación',
         'B': 'solo más capas sin datos',
         'C': 'sin validación',
         'D': 'solo train loss',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Gradiente descendente estocástico usa:',
         'A': 'mini-lotes',
         'B': 'dataset completo siempre',
         'C': 'sin gradiente',
         'D': 'solo RL sin recompensa',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'SVM con kernel implícito mapea a:',
         'A': 'espacio de mayor dimensión',
         'B': 'siempre 1D',
         'C': 'sin margen',
         'D': 'sin convexidad',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Entropía cruzada en clasificación mide:',
         'A': 'discrepancia entre predicción y etiqueta',
         'B': 'solo distancia euclídea',
         'C': 'solo FFT',
         'D': 'solo TLS',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Dropout en entrenamiento de redes:',
         'A': 'desactiva neuronas aleatoriamente',
         'B': 'aumenta siempre overfit',
         'C': 'sin backprop',
         'D': 'sin pesos',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'CNN explota:',
         'A': 'invariancia local y jerarquía espacial',
         'B': 'solo series sin convolución',
         'C': 'solo SQL',
         'D': 'solo CAP',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Backpropagation calcula:',
         'A': 'gradientes por regla cadena',
         'B': 'solo forward',
         'C': 'sin pérdida',
         'D': 'solo clustering',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Reinforcement learning optimiza:',
         'A': 'recompensa acumulada esperada',
         'B': 'solo MSE supervisado',
         'C': 'solo SQL',
         'D': 'solo HTML',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Attention en Transformers pondera:',
         'A': 'relevancia entre tokens',
         'B': 'solo conv 3×3',
         'C': 'solo PageRank',
         'D': 'solo LU',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Batch normalization estabiliza:',
         'A': 'activaciones por capa',
         'B': 'solo pesos iniciales sin datos',
         'C': 'solo test siempre',
         'D': 'solo MQTT',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Precisión vs recall: alto recall implica:',
         'A': 'pocos falsos negativos',
         'B': 'pocos falsos positivos siempre',
         'C': 'sin FN ni FP',
         'D': 'sin umbral',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un árbol de decisión divide por:',
         'A': 'criterio de impureza (Gini, entropía)',
         'B': 'solo aleatorio sin ganancia',
         'C': 'solo TLS',
         'D': 'solo FFT',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'k-means minimiza:',
         'A': 'inercia intra-cluster',
         'B': 'solo entropía cruzada',
         'C': 'solo PageRank',
         'D': 'solo Poisson',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Transfer learning reutiliza:',
         'A': 'representaciones de modelo preentrenado',
         'B': 'solo datos sintéticos vacíos',
         'C': 'sin fine-tuning',
         'D': 'solo SQL',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'GAN entrena:',
         'A': 'generador y discriminador adversarios',
         'B': 'solo autoencoder lineal',
         'C': 'solo SVM',
         'D': 'solo Dijkstra',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'LSTM mitiga:',
         'A': 'desvanecimiento de gradiente en secuencias',
         'B': 'solo imágenes estáticas',
         'C': 'solo CAP',
         'D': 'solo RAID',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Visión por computador: convolución implementa:',
         'A': 'filtros locales compartidos',
         'B': 'solo joins SQL',
         'C': 'solo TLS',
         'D': 'solo MQTT',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'ROC-AUC resume:',
         'A': 'capacidad de ranking sobre umbrales',
         'B': 'solo accuracy',
         'C': 'solo loss train',
         'D': 'solo FFT',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Early stopping monitoriza:',
         'A': 'métrica en validación',
         'B': 'solo train infinito',
         'C': 'sin validación',
         'D': 'sin épocas',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Embeddings densos representan:',
         'A': 'entidades en vector continuo',
         'B': 'solo one-hot sin dimensión',
         'C': 'solo matrices ortogonales obligadas',
         'D': 'solo DNS',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Aprendizaje semi-supervisado usa:',
         'A': 'pocos etiquetados y muchos no etiquetados',
         'B': 'solo etiquetados',
         'C': 'sin datos',
         'D': 'solo RL puro',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'ViT divide imagen en:',
         'A': 'parches tratados como tokens',
         'B': 'solo píxeles sin atención',
         'C': 'solo SQL',
         'D': 'solo LU',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Data leakage ocurre si:',
         'A': 'información de test influye entrenamiento',
         'B': 'validación correcta',
         'C': 'shuffle adecuado',
         'D': 'sin features',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
    ],
    'Metodes Numerics i Optimitzacio': [
        {'pregunta': 'El método de Newton para raíces usa:',
         'A': "x_{n+1}=x_n - f(x_n)/f'(x_n)",
         'B': 'solo Euler',
         'C': 'solo Gauss-Seidel sin función',
         'D': 'solo FFT',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Calculo'}
,
        {'pregunta': 'Integración Monte Carlo estima integrales por:',
         'A': 'promedio de muestras aleatorias',
         'B': 'solo regla del trapecio determinista',
         'C': 'solo LU',
         'D': 'solo TLS',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Gradiente descendente minimiza f actualizando:',
         'A': 'x -= η ∇f(x)',
         'B': 'x += ∇f sin η',
         'C': 'solo autovalores',
         'D': 'solo hash',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Calculo'}
,
        {'pregunta': 'Condicionamiento de matriz alto implica:',
         'A': 'sensibilidad a errores numéricos',
         'B': 'siempre bien condicionado',
         'C': 'det=1',
         'D': 'rango=0',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Gauss-Seidel itera usando:',
         'A': 'valores actualizados inmediatamente',
         'B': 'solo valores antiguos siempre',
         'C': 'sin diagonal',
         'D': 'sin convergencia nunca',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'QR por Gram-Schmidt estabilizado usa:',
         'A': 'Householder o reflexiones',
         'B': 'solo potencias sucesivas sin ortogonalizar',
         'C': 'solo Monte Carlo',
         'D': 'solo MQTT',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un problema de optimización convexo tiene:',
         'A': 'mínimo global si factible',
         'B': 'siempre múltiples mínimos no convexos',
         'C': 'sin restricciones siempre',
         'D': 'sin gradiente',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Programación lineal simplex explora:',
         'A': 'vértices factibles',
         'B': 'solo interior aleatorio',
         'C': 'solo grafos',
         'D': 'solo TLS',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Método de Runge-Kutta 4 para ODEs es:',
         'A': 'de cuarto orden local',
         'B': 'de primer orden siempre',
         'C': 'sin paso h',
         'D': 'sin f',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Interpolación spline cúbica busca:',
         'A': 'continuidad C² en nodos',
         'B': 'solo constante',
         'C': 'solo lineal global',
         'D': 'sin nodos',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Multigrid acelera:',
         'A': 'solución de sistemas elípticos discretos',
         'B': 'solo sorting',
         'C': 'solo TLS',
         'D': 'solo MQTT',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Simulación HPC en cluster usa:',
         'A': 'MPI/OpenMP u similares',
         'B': 'solo hoja Excel',
         'C': 'solo DNS',
         'D': 'solo CSS',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Método de potencias aproxima:',
         'A': 'autovector dominante',
         'B': 'todos los autovalores exactos siempre',
         'C': 'solo LU',
         'D': 'solo join SQL',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Lagrangianos en optimización con restricciones introducen:',
         'A': 'multiplicadores',
         'B': 'solo RNG',
         'C': 'solo GPU texture',
         'D': 'solo HTML',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Line search en optimización elige:',
         'A': 'paso α que reduzca f suficientemente',
         'B': 'α infinito siempre',
         'C': 'sin evaluar f',
         'D': 'solo FFT',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Error de truncamiento en diferencias finitas depende de:',
         'A': 'paso h y orden del esquema',
         'B': 'solo color',
         'C': 'solo MAC',
         'D': 'solo TLS',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Método del gradiente conjugado es eficaz para:',
         'A': 'sistemas simétricos definidos positivos',
         'B': 'cualquier matriz singular siempre',
         'C': 'solo grafos',
         'D': 'solo IoT',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Cuasi-Newton BFGS aproxima:',
         'A': 'Hessiana o su inversa',
         'B': 'solo identidad siempre',
         'C': 'sin gradiente',
         'D': 'sin línea',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Integración adaptativa ajusta:',
         'A': 'subdivisiones según error estimado',
         'B': 'paso fijo infinito',
         'C': 'sin evaluaciones',
         'D': 'solo RSA',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Simulación estocástica SDE usa:',
         'A': 'métodos de Euler-Maruyama u superiores',
         'B': 'solo Laplace determinista',
         'C': 'solo SQL',
         'D': 'solo CSS',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Optimización no lineal con restricciones KKT requiere:',
         'A': 'estacionariedad y factibilidad complementaria',
         'B': 'solo RNG',
         'C': 'solo UI',
         'D': 'solo FFT',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Descomposición LU con pivoteo mejora:',
         'A': 'estabilidad numérica',
         'B': 'siempre empeora',
         'C': 'rango infinito',
         'D': 'sin permutaciones',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Varianza reducida en Monte Carlo usa:',
         'A': 'variables de control/importance sampling',
         'B': 'solo duplicar h',
         'C': 'solo TLS',
         'D': 'solo MQTT',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
    ],
    'Modelitzacio Fisica i Informacio': [
        {'pregunta': 'La entropía de Shannon H(X)=',
         'A': '-Σ p(x) log p(x)',
         'B': 'Σ p(x)^2',
         'C': 'det(A)',
         'D': 'solo FFT',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Capacidad de canal C en AWGN relaciona:',
         'A': 'ancho de banda y SNR',
         'B': 'solo CPU',
         'C': 'solo GPU',
         'D': 'solo SQL',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Segunda ley termodinámica implica:',
         'A': 'entropía aislada no decrece',
         'B': 'energía crea orden sin coste',
         'C': 'caos cero',
         'D': 'sin temperatura',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Simulación molecular integra:',
         'A': 'ecuaciones de movimiento de partículas',
         'B': 'solo PageRank',
         'C': 'solo TLS',
         'D': 'solo MQTT',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Qubit puede estar en:',
         'A': 'superposición de |0⟩ y |1⟩',
         'B': 'solo 0 clásico',
         'C': 'solo 1 clásico',
         'D': 'sin probabilidad',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Medida en base computacional colapsa:',
         'A': 'estado a autovector medido',
         'B': 'siempre mezcla uniforme',
         'C': 'sin probabilidad',
         'D': 'sin Born',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Código de Hamming detecta/corrige:',
         'A': 'errores de bits',
         'B': 'solo latencia HTTP',
         'C': 'solo UI',
         'D': 'solo CSS',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Teorema de Nyquist para muestreo requiere:',
         'A': 'fs > 2 fmax (banda limitada)',
         'B': 'fs = 0',
         'C': 'sin señal',
         'D': 'solo discreto sin analógico',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Ecuación de Schrödinger gobierna:',
         'A': 'evolución de función de onda',
         'B': 'solo fluido Navier-Stokes clásico',
         'C': 'solo SQL',
         'D': 'solo HTML',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Modelo Ising describe:',
         'A': 'spines en red con interacción',
         'B': 'solo grafos sin energía',
         'C': 'solo TLS',
         'D': 'solo RAID',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Compresión sin pérdida usa:',
         'A': 'códigos entrópicos/Huffman u aritméticos',
         'B': 'solo borrar datos',
         'C': 'solo JPEG siempre',
         'D': 'solo dropout',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Entrelazamiento cuántico implica:',
         'A': 'correlaciones no clásicas',
         'B': 'solo bits independientes',
         'C': 'sin medida',
         'D': 'sin estado',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Simulación de Monte Carlo en física estima:',
         'A': 'promedios de observables estocásticos',
         'B': 'solución analítica siempre',
         'C': 'sin RNG',
         'D': 'solo LU',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Ley de Stefan-Boltzmann relaciona:',
         'A': 'potencia radiada y temperatura',
         'B': 'solo entropía de Shannon',
         'C': 'solo SQL',
         'D': 'solo CSS',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Información mutua I(X;Y) mide:',
         'A': 'dependencia estadística',
         'B': 'solo distancia euclídea',
         'C': 'solo FFT UI',
         'D': 'solo CAP',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Agentes en simulación ABM interactúan:',
         'A': 'localmente según reglas',
         'B': 'solo ecuación única global',
         'C': 'sin estado',
         'D': 'solo TLS',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Teorema de no-clonación en cuántica:',
         'A': 'no clonar estados desconocidos arbitrarios',
         'B': 'clonar cualquier qubit',
         'C': 'sin medida',
         'D': 'sin entrelazamiento',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Ecuaciones de Maxwell unifican:',
         'A': 'campos eléctrico y magnético',
         'B': 'solo Poisson de BD',
         'C': 'solo PageRank',
         'D': 'solo MQTT',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Ruido térmico en sensores afecta:',
         'A': 'relación señal-ruido',
         'B': 'solo UI',
         'C': 'solo HTML',
         'D': 'solo git',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Modelado de fluidos CFD resuelve:',
         'A': 'Navier-Stokes discretizado',
         'B': 'solo álgebra booleana',
         'C': 'solo SQL',
         'D': 'solo CSS',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'LDPC en comunicaciones son:',
         'A': 'códigos de paridad de baja densidad',
         'B': 'solo hashes de passwords',
         'C': 'solo B-tree',
         'D': 'solo FFT UI',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Principio de incertidumbre de Heisenberg limita:',
         'A': 'precisión simultánea de variables conjugadas',
         'B': 'velocidad de luz en fibra',
         'C': 'solo CPU',
         'D': 'solo GPU',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Simulación en paralelo domain decomposition divide:',
         'A': 'dominio espacial entre procesos',
         'B': 'solo un hilo',
         'C': 'sin comunicación',
         'D': 'solo MQTT',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
    ],
    'Probabilitat i Ciencia de Dades': [
        {'pregunta': 'La esperanza E[X] para discreta es:',
         'A': 'Σ x P(X=x)',
         'B': 'solo máximo',
         'C': 'solo mediana siempre',
         'D': 'det(A)',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Var(X)=E[X²]-(E[X])² requiere:',
         'A': 'momentos finitos',
         'B': 'X constante siempre',
         'C': 'sin probabilidad',
         'D': 'solo Bayes',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Calculo'}
,
        {'pregunta': 'Teorema de Bayes: P(A|B)=',
         'A': 'P(B|A)P(A)/P(B)',
         'B': 'P(A)+P(B)',
         'C': 'P(A)-P(B)',
         'D': '1 siempre',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Una distribución Normal estándar tiene:',
         'A': 'media 0 varianza 1',
         'B': 'media 1 var 0',
         'C': 'solo cola gruesa',
         'D': 'sin PDF',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La ley de los grandes números dice:',
         'A': 'media muestral converge a esperanza',
         'B': 'siempre diverge',
         'C': 'sin muestras',
         'D': 'solo cero',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'El estimador MLE maximiza:',
         'A': 'verosimilitud de datos',
         'B': 'solo prior',
         'C': 'solo error UI',
         'D': 'solo FFT',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un p-valor pequeño sugiere:',
         'A': 'evidencia contra H0 (interpretación frecuentista)',
         'B': 'aceptar H0 siempre',
         'C': 'sin datos',
         'D': 'causalidad',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Regresión lineal minimiza típicamente:',
         'A': 'suma de cuadrados de residuos',
         'B': 'solo entropía cruzada',
         'C': 'solo PageRank',
         'D': 'solo TLS',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Calculo'}
,
        {'pregunta': 'Correlación de Pearson mide:',
         'A': 'asociación lineal',
         'B': 'causalidad',
         'C': 'independencia siempre',
         'D': 'solo categórica',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Validación cruzada k-fold sirve para:',
         'A': 'estimar error de generalización',
         'B': 'entrenar sin test',
         'C': 'solo overfit',
         'D': 'solo GPU',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Bootstrap remuestrea:',
         'A': 'con reemplazo de la muestra',
         'B': 'sin datos',
         'C': 'solo prior fijo',
         'D': 'solo SQL',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Una cadena de Markov sin memoria cumple:',
         'A': 'P(X_{t+1}|X_t,...)=P(X_{t+1}|X_t)',
         'B': 'siempre iid global',
         'C': 'sin estados',
         'D': 'solo continuo',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Poisson modela:',
         'A': 'conteos en intervalo fijo',
         'B': 'solo alturas continuas',
         'C': 'solo matrices',
         'D': 'solo TLS',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Test chi-cuadrado de independencia usa:',
         'A': 'tabla contingencia',
         'B': 'solo FFT',
         'C': 'solo gradiente',
         'D': 'solo CAP',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Overfitting ocurre cuando:',
         'A': 'modelo memoriza ruido de entrenamiento',
         'B': 'error train alto',
         'C': 'sin parámetros',
         'D': 'datos infinitos siempre',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Regularización L2 penaliza:',
         'A': 'norma de pesos al cuadrado',
         'B': 'solo sesgo',
         'C': 'solo dropout',
         'D': 'solo TLS',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Análisis de series temporales ARIMA combina:',
         'A': 'AR, I, MA',
         'B': 'solo CNN',
         'C': 'solo RSA',
         'D': 'solo LU',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'PCA busca direcciones de:',
         'A': 'máxima varianza proyectada',
         'B': 'mínima entropía siempre',
         'C': 'solo clasificación',
         'D': 'solo TLS',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un intervalo de confianza 95% significa (frecuentista):',
         'A': 'procedimiento con 95% cobertura a largo plazo',
         'B': '95% prob del parámetro fijo',
         'C': 'sin muestra',
         'D': 'causal',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La divergencia KL mide:',
         'A': 'diferencia entre distribuciones',
         'B': 'solo distancia euclídea',
         'C': 'solo FFT',
         'D': 'solo MQTT',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Datos desbalanceados en clasificación se tratan con:',
         'A': 'pesos, oversampling, métricas adecuadas',
         'B': 'ignorar minoría',
         'C': 'solo accuracy',
         'D': 'sin métricas',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Inferencia bayesiana actualiza:',
         'A': 'posterior con verosimilitud y prior',
         'B': 'solo MLE siempre',
         'C': 'sin datos',
         'D': 'solo UI',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Persistencia homológica en TDA resume:',
         'A': 'características multiescala de forma de datos',
         'B': 'solo SQL joins',
         'C': 'solo TLS',
         'D': 'solo RAID',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
    ],
    'Programacio de Software': [
        {'pregunta': 'El principio DRY significa:',
         'A': 'no repetir conocimiento/lógica innecesariamente',
         'B': 'duplicar todo',
         'C': 'sin tests',
         'D': 'sin interfaces',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un test unitario típicamente verifica:',
         'A': 'una unidad aislada con mocks si hace falta',
         'B': 'toda la red distribuida',
         'C': 'solo UI manual',
         'D': 'solo GPU',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La inversión de dependencias (SOLID) sugiere:',
         'A': 'depender de abstracciones',
         'B': 'depender de concretos siempre',
         'C': 'sin interfaces',
         'D': 'globals everywhere',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'CI/CD automatiza:',
         'A': 'integración y despliegue continuos',
         'B': 'solo diseño Figma',
         'C': 'solo teoría de grupos',
         'D': 'solo minería',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un patrón Observer notifica:',
         'A': 'cambios a suscriptores',
         'B': 'solo CPU',
         'C': 'solo DNS',
         'D': 'solo FFT',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Refactoring seguro requiere:',
         'A': 'tests que cubran comportamiento',
         'B': 'sin control de versiones',
         'C': 'sin compilación',
         'D': 'solo comentarios',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'API REST usa recursos identificados por:',
         'A': 'URIs y verbos HTTP',
         'B': 'solo RPC binario obligatorio',
         'C': 'solo sockets raw',
         'D': 'solo SQL embebido',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La encapsulación en OOP oculta:',
         'A': 'detalle interno del objeto',
         'B': 'todo el programa',
         'C': 'solo main',
         'D': 'solo hardware',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Polimorfismo permite:',
         'A': 'tratar objetos de subtipos uniformemente',
         'B': 'solo matrices',
         'C': 'solo integrales',
         'D': 'solo hashes',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un mutex evita:',
         'A': 'condiciones de carrera en sección crítica',
         'B': 'memory leaks siempre',
         'C': 'deadlocks siempre',
         'D': 'compilación',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': "Code smell 'God class' indica:",
         'A': 'clase con demasiadas responsabilidades',
         'B': 'clase perfecta',
         'C': 'sin métodos',
         'D': 'sin atributos',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'TDD escribe tests:',
         'A': 'antes o junto al diseño esperado',
         'B': 'nunca',
         'C': 'solo tras producción sin tests',
         'D': 'solo manual',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Semántica de excepciones checked (Java) obliga a:',
         'A': 'declarar o capturar',
         'B': 'ignorar siempre',
         'C': 'sin try',
         'D': 'solo assert',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un contenedor Docker empaqueta:',
         'A': 'app y dependencias aisladas',
         'B': 'solo kernel host',
         'C': 'solo FPGA',
         'D': 'solo latex',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Versionado semántico MAJOR.MINOR.PATCH indica breaking en:',
         'A': 'MAJOR',
         'B': 'PATCH siempre',
         'C': 'MINOR siempre',
         'D': 'ninguno',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'OpenAPI describe:',
         'A': 'contratos HTTP de APIs',
         'B': 'solo binarios',
         'C': 'solo GPU',
         'D': 'solo PDE',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Pair programming busca:',
         'A': 'revisión continua y conocimiento compartido',
         'B': 'sin teclado',
         'C': 'sin comunicación',
         'D': 'solo métricas CAP',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un pipeline de build suele incluir:',
         'A': 'compilar, test, empaquetar',
         'B': 'solo minar',
         'C': 'solo FFT',
         'D': 'solo Poisson',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La complejidad ciclomática mide:',
         'A': 'caminos independientes en grafo de control',
         'B': 'líneas de comentarios',
         'C': 'tamaño de RAM',
         'D': 'latencia red',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Inyección SQL se previene con:',
         'A': 'consultas parametrizadas',
         'B': 'concatenar strings de usuario',
         'C': 'sin BD',
         'D': 'solo HTTP GET',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un enum en tipos seguros evita:',
         'A': 'valores mágicos inválidos',
         'B': 'toda abstracción',
         'C': 'toda compilación',
         'D': 'toda red',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Feature flags permiten:',
         'A': 'activar funcionalidad sin redeploy completo',
         'B': 'eliminar git',
         'C': 'sin logs',
         'D': 'sin usuarios',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Clean Architecture enfatiza:',
         'A': 'dependencias hacia el dominio',
         'B': 'UI en el centro',
         'C': 'BD en el centro siempre',
         'D': 'sin casos de uso',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
    ],
    'Sistemes i Seguretat Computacional': [
        {'pregunta': 'En sistemas distribuidos, el teorema CAP afirma que bajo partición de red no puedes garantizar '
                     'simultáneamente:',
         'A': 'consistencia fuerte y disponibilidad total',
         'B': 'solo latencia',
         'C': 'solo RAID',
         'D': 'caché L1',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un reloj vectorial en mensajería distribuida sirve para:',
         'A': 'orden parcial de eventos',
         'B': 'cifrar AES',
         'C': 'compilar C',
         'D': 'entrenar redes',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'TLS proporciona principalmente:',
         'A': 'confidencialidad e integridad en tránsito',
         'B': 'almacenamiento en disco cifrado',
         'C': 'scheduling de CPU',
         'D': 'indexación SQL',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un ataque de repetición en protocolos se mitiga con:',
         'A': 'nonces o timestamps',
         'B': 'solo compresión gzip',
         'C': 'más RAM',
         'D': 'UDP sin estado',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La arquitectura de microservicios favorece:',
         'A': 'despliegue independiente por servicio',
         'B': 'monolito único obligatorio',
         'C': 'sin APIs',
         'D': 'sin balanceo',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Kubernetes orquesta principalmente:',
         'A': 'contenedores y pods',
         'B': 'solo bases relacionales',
         'C': 'solo GPUs de entrenamiento',
         'D': 'compiladores',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un hypervisor Tipo 1 corre:',
         'A': 'directamente sobre hardware',
         'B': 'solo como app de usuario',
         'C': 'sin virtualización',
         'D': 'solo en IoT sin red',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La autenticación multifactor combina:',
         'A': 'factores de distinta categoría',
         'B': 'solo contraseñas largas repetidas',
         'C': 'solo IP pública',
         'D': 'solo MAC',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un firewall de capa 7 puede inspeccionar:',
         'A': 'contenido de aplicación HTTP',
         'B': 'solo bits físicos',
         'C': 'solo temperatura',
         'D': 'solo FFT',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'El modelo de amenazas STRIDE incluye:',
         'A': 'suplantación, alteración, repudio, etc.',
         'B': 'solo sorting',
         'C': 'solo clustering',
         'D': 'solo Monte Carlo',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'En IoT, MQTT es un protocolo de:',
         'A': 'mensajería pub/sub ligera',
         'B': 'minado de criptomonedas',
         'C': 'render 3D',
         'D': 'álgebra lineal',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La escalabilidad horizontal añade:',
         'A': 'más nodos similares',
         'B': 'solo CPU más rápida en un nodo',
         'C': 'solo disco en un servidor',
         'D': 'solo caché local',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un consenso Raft elige:',
         'A': 'líder para replicación de log',
         'B': 'solo GPU',
         'C': 'solo hash MD5 sin sal',
         'D': 'solo DNS',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Side-channel attacks explotan:',
         'A': 'filtraciones físicas o temporales',
         'B': 'solo errores de sintaxis',
         'C': 'solo UI',
         'D': 'solo HTML',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Zero Trust asume:',
         'A': 'verificar cada solicitud',
         'B': 'confiar en la red interna siempre',
         'C': 'sin autenticación',
         'D': 'solo VPN legacy',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un sistema eventualmente consistente puede:',
         'A': 'mostrar estados obsoletos temporalmente',
         'B': 'nunca converger',
         'C': 'violar física',
         'D': 'ser siempre ACID fuerte',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'La virtualización de red SDN separa:',
         'A': 'plano de control y de datos',
         'B': 'CPU y GPU siempre',
         'C': 'train y test',
         'D': 'kernel e imagen',
         'correcta': 'A',
         'dificultad': 'Dificil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'HMAC garantiza:',
         'A': 'integridad y autenticación de mensaje con clave',
         'B': 'confidencialidad sin clave',
         'C': 'anonimato perfecto',
         'D': 'compresión',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un DDoS busca:',
         'A': 'agotar recursos del servicio',
         'B': 'mejorar latencia',
         'C': 'optimizar queries',
         'D': 'entrenar modelos',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'El principio de mínimo privilegio implica:',
         'A': 'otorgar solo permisos necesarios',
         'B': 'admin root siempre',
         'C': 'contraseña vacía',
         'D': 'abrir todos los puertos',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Sharding en bases distribuidas reparte:',
         'A': 'datos por particiones',
         'B': 'solo logs de kernel',
         'C': 'solo imágenes',
         'D': 'solo RAM L1',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Un sandbox de procesos limita:',
         'A': 'superficie de ataque del código',
         'B': 'ancho de banda de Fibonacci',
         'C': 'solo color UI',
         'D': 'solo teclado',
         'correcta': 'A',
         'dificultad': 'Media',
         'tipo': 'Teoria'}
,
        {'pregunta': 'Observabilidad en cloud combina:',
         'A': 'métricas, logs y trazas',
         'B': 'solo printf',
         'C': 'solo XOR',
         'D': 'solo RAID0',
         'correcta': 'A',
         'dificultad': 'Facil',
         'tipo': 'Teoria'}
,
    ],
}

def _sufijo_materia(materia: str) -> str:
    """Sufijo único por materia (misma temática, enunciados diferenciados)."""
    return f" [{materia}]"


def entradas_internet_para_materia(materia: str) -> list[dict]:
    """Devuelve copias del banco de la temática de la materia con prefijo en pregunta."""
    if materia not in MATERIA_TEMATICA:
        raise KeyError(f"Materia desconocida: {materia!r}")
    tematica = MATERIA_TEMATICA[materia]
    banco = BANCO_POR_TEMATICA[tematica]
    sufijo = _sufijo_materia(materia)
    salida: list[dict] = []
    for entrada in banco:
        copia = dict(entrada)
        copia["pregunta"] = entrada["pregunta"] + sufijo
        salida.append(copia)
    return salida


def fusionar_con_repuesto(materia: str) -> list[dict]:
    """REPUESTO_CATALOGO[materia] + entradas internet con campo uso="internet"."""
    repuesto = [dict(e) for e in REPUESTO_CATALOGO.get(materia, [])]
    internet = []
    for e in entradas_internet_para_materia(materia):
        copia = dict(e)
        copia["uso"] = "internet"
        internet.append(copia)
    return repuesto + internet
