# -*- coding: utf-8 -*-
"""
Plantillas de repuesto: subtemas que NO deben duplicar el dataset activo (12 preguntas por materia en CSV).
Cada entrada lleva ``etiquetas`` (palabras clave); solo se inyecta si ninguna aparece
en las 12 preguntas publicadas de esa materia.
"""

from __future__ import annotations

from pathlib import Path

BASE = Path(__file__).resolve().parent.parent

# Formato: lista de dicts con pregunta, A, B, C, D, correcta, dificultad, tipo, etiquetas

REPUESTO_CATALOGO: dict[str, list[dict]] = {
    "Àlgebra Lineal": [
        {
            "etiquetas": ["kernel", "núcleo"],
            "pregunta": "¿Qué es el núcleo (kernel) de una aplicación lineal T?",
            "A": "Vectores que T envía al vector cero",
            "B": "El conjunto de autovalores",
            "C": "La dimensión del espacio imagen",
            "D": "El determinante de la matriz",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["proyección ortogonal"],
            "pregunta": "Una proyección ortogonal P en un espacio con producto escalar cumple típicamente:",
            "A": "P² = P y P es autoadjunta (simétrica en ℝⁿ)",
            "B": "det(P) = 0 siempre",
            "C": "P es siempre diagonal con unos en la diagonal",
            "D": "P no es lineal",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
    ],
    "Càlcul en una Variable": [
        {
            "etiquetas": ["regla cadena"],
            "pregunta": "¿Para qué sirve la regla de la cadena?",
            "A": "Derivar composiciones f(g(x))",
            "B": "Integrar por partes siempre",
            "C": "Calcular límites de sucesiones",
            "D": "Desarrollar series de Taylor sin derivadas",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["continuidad"],
            "pregunta": "¿Qué significa que f sea continua en un punto a?",
            "A": "lim_{x→a} f(x) = f(a)",
            "B": "f'(a) existe siempre",
            "C": "f es derivable en todo ℝ",
            "D": "La integral de f es cero",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
    ],
    "Fonaments de Computadors": [
        {
            "etiquetas": ["von neumann"],
            "pregunta": "¿Qué caracteriza la arquitectura de von Neumann?",
            "A": "Programa y datos en la misma memoria direccionable",
            "B": "Solo memoria ROM sin RAM",
            "C": "Sin unidad aritmético-lógica",
            "D": "Procesamiento solo vectorial en GPU",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["localidad temporal"],
            "pregunta": "¿Qué es la localidad temporal en acceso a memoria?",
            "A": "Reutilizar pronto los mismos datos o instrucciones",
            "B": "Acceder siempre a direcciones aleatorias lejanas",
            "C": "Duplicar el reloj del procesador",
            "D": "Eliminar la caché",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Iniciació a la Programació": [
        {
            "etiquetas": ["parámetro", "parametro"],
            "pregunta": "¿Qué es un parámetro de una función?",
            "A": "Variable de entrada declarada en la definición de la función",
            "B": "El valor devuelto obligatoriamente",
            "C": "Un tipo de excepción",
            "D": "Un archivo de configuración del SO",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["función", "def"],
            "pregunta": "¿Qué es una función en programación?",
            "A": "Bloque reutilizable con nombre que puede recibir parámetros y devolver un valor",
            "B": "Un tipo de bucle exclusivo de C",
            "C": "Un archivo binario ejecutable",
            "D": "Una tabla de base de datos",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["módulo", "import"],
            "pregunta": "¿Para qué sirve importar un módulo en Python?",
            "A": "Usar código definido en otro archivo o librería",
            "B": "Borrar variables globales",
            "C": "Compilar a ensamblador obligatoriamente",
            "D": "Crear procesos paralelos MPI",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Programari de Sistema": [
        {
            "etiquetas": ["terminal", "shell"],
            "pregunta": "¿Qué es un terminal en un sistema Unix?",
            "A": "Interfaz para introducir comandos al shell",
            "B": "El núcleo del sistema operativo",
            "C": "Un compilador de Fortran",
            "D": "Un índice B+ de base de datos",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["pipe", "redirección"],
            "pregunta": "En Unix, ¿qué hace el operador pipe | entre dos comandos?",
            "A": "Envía la salida estándar del primero a la entrada del segundo",
            "B": "Copia archivos binarios",
            "C": "Monta un sistema de ficheros",
            "D": "Compila con gcc",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["chmod", "permisos"],
            "pregunta": "¿Qué cambia el comando chmod en Unix?",
            "A": "Los permisos de lectura/escritura/ejecución de archivos",
            "B": "La contraseña del usuario root siempre",
            "C": "El código fuente de un programa Python",
            "D": "La tabla de rutas OSPF",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["git", "repositorio"],
            "pregunta": "¿Qué es un repositorio Git?",
            "A": "Almacén con historial de versiones del proyecto",
            "B": "Un proceso del kernel",
            "C": "Un tipo de socket TCP",
            "D": "Una tabla SQL",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
    ],
    "Algorítmia i Combinatòria en Grafs. Mètodes Heurístics": [
        {
            "etiquetas": ["camino mínimo"],
            "pregunta": "En un grafo con pesos no negativos, ¿qué problema resuelve Dijkstra desde s?",
            "A": "Distancias mínimas desde s a cada vértice alcanzable",
            "B": "Un árbol de expansión máximo",
            "C": "El número cromático del grafo",
            "D": "Un matching bipartito perfecto",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Càlcul en Diverses Variables": [
        {
            "etiquetas": ["punto crítico"],
            "pregunta": "¿Cuándo (a,b) es punto crítico de f(x,y)?",
            "A": "Cuando ∂f/∂x=0 y ∂f/∂y=0 (si existen)",
            "B": "Cuando f(a,b)=0",
            "C": "Cuando el gradiente es máximo",
            "D": "Solo si f es lineal",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["hessiana"],
            "pregunta": "La matriz Hessiana de f(x,y) recoge:",
            "A": "Las derivadas parciales segundas de f",
            "B": "Solo las primeras derivadas",
            "C": "La integral doble de f",
            "D": "El jacobiano de una función vectorial",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
    ],
    "Càlcul Numèric": [
        {
            "etiquetas": ["trapecio", "regla del trapecio"],
            "pregunta": "La regla del trapecio aproxima una integral:",
            "A": "Sustituyendo el área bajo f por trapecios en subintervalos",
            "B": "Resolviendo siempre la EDO exactamente",
            "C": "Diagonalizando matrices simétricas",
            "D": "Calculando autovalores con QR",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["jacobi"],
            "pregunta": "El método iterativo de Jacobi se usa para:",
            "A": "Resolver sistemas lineales Ax=b de forma iterativa",
            "B": "Entrenar redes neuronales convolucionales",
            "C": "Codificar mensajes con Huffman",
            "D": "Simular tráfico MQTT",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["bisección", "biseccion"],
            "pregunta": "El método de bisección para encontrar raíces requiere:",
            "A": "Un intervalo [a,b] donde f cambia de signo",
            "B": "Que f sea lineal en todo ℝ",
            "C": "Conocer la derivada segunda",
            "D": "Una matriz hessiana definida positiva",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Probabilitat": [
        {
            "etiquetas": ["bayes"],
            "pregunta": "El teorema de Bayes relaciona P(A|B) con:",
            "A": "P(B|A), P(A) y P(B)",
            "B": "Solo la media de A",
            "C": "La varianza de B únicamente",
            "D": "El determinante de una matriz",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["contraste de hipótesis"],
            "pregunta": "¿Qué contrasta un test de hipótesis clásico?",
            "A": "Si los datos son compatibles con H0 frente a H1",
            "B": "Si la muestra es infinita",
            "C": "Si la regresión es lineal",
            "D": "Si el grafo es bipartito",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Programació Orientada als Objectes": [
        {
            "etiquetas": ["encapsulación"],
            "pregunta": "¿Qué es la encapsulación en POO?",
            "A": "Ocultar detalles internos y exponer una interfaz controlada",
            "B": "Herencia múltiple obligatoria",
            "C": "Ejecutar código en GPU",
            "D": "Serializar a JSON siempre",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["interface", "interfaz"],
            "pregunta": "¿Qué es una interfaz en POO?",
            "A": "Contrato de métodos que una clase puede implementar",
            "B": "Un archivo de log del sistema",
            "C": "Un tipo de join SQL",
            "D": "Un kernel de convolución",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["herencia"],
            "pregunta": "¿Qué es la herencia en POO?",
            "A": "Una clase deriva atributos y métodos de otra",
            "B": "Ejecutar dos hilos a la vez",
            "C": "Cifrar un mensaje",
            "D": "Ordenar un array in-place",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["polimorfismo"],
            "pregunta": "¿Qué es el polimorfismo en POO?",
            "A": "Misma interfaz con implementaciones distintas",
            "B": "Copiar código sin clases",
            "C": "Compilar a bytecode sin clases",
            "D": "Un tipo de base de datos",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Bases de Dades Relacionals": [
        {
            "etiquetas": ["join"],
            "pregunta": "¿Qué hace un JOIN en SQL?",
            "A": "Combina filas de tablas según una condición de relación",
            "B": "Borra todas las filas",
            "C": "Cifra la base de datos",
            "D": "Compila Java",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["acid", "transacciones"],
            "pregunta": "En ACID, la «A» de Atomicidad significa que una transacción:",
            "A": "Se ejecuta toda o no se ejecuta (rollback si falla)",
            "B": "Siempre es paralela en GPU",
            "C": "No usa índices",
            "D": "Es solo lectura obligatoria",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Equacions Diferencials Ordinàries": [
        {
            "etiquetas": ["autónoma", "autonoma"],
            "pregunta": "Una EDO autónoma tiene la forma:",
            "A": "y' = f(y) sin dependencia explícita de t",
            "B": "y'' + y = 0 siempre",
            "C": "u_t = u_xx",
            "D": "F = m·a",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["picard", "existencia"],
            "pregunta": "El teorema de Picard-Lindelöf garantiza bajo hipótesis habituales:",
            "A": "Existencia y unicidad local de solución de y'=f(t,y)",
            "B": "Solución global para cualquier f discontinua",
            "C": "Que la EDP sea elíptica",
            "D": "Convergencia de una serie de Fourier",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["runge-kutta"],
            "pregunta": "Los métodos Runge-Kutta para EDO son:",
            "A": "Métodos numéricos de paso para aproximar soluciones",
            "B": "Soluciones exactas por separación de variables siempre",
            "C": "Solo para EDP elípticas",
            "D": "Algoritmos de ordenamiento",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Modelització i Inferència": [
        {
            "etiquetas": ["intervalo confianza"],
            "pregunta": "¿Qué es un intervalo de confianza del 95% para un parámetro?",
            "A": "Rango calculado a partir de la muestra que cubre el parámetro con método del 95%",
            "B": "Probabilidad 95% de que los datos sean normales",
            "C": "Siempre coincide con la media muestral",
            "D": "Un test de hipótesis bilateral",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["bootstrap"],
            "pregunta": "En bootstrap, ¿qué se remuestrea típicamente?",
            "A": "La muestra observada con reemplazo para estimar la variabilidad",
            "B": "Solo los parámetros poblacionales conocidos",
            "C": "Las etiquetas de clase sin datos",
            "D": "La matriz de diseño sin filas",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Tècniques de Disseny d'Algoritmes": [
        {
            "etiquetas": ["programación dinámica"],
            "pregunta": "¿Cuándo suele aplicarse programación dinámica?",
            "A": "Subproblemas superpuestos y subestructura óptima",
            "B": "Solo grafos sin pesos",
            "C": "Cuando no hay recurrencia",
            "D": "Solo búsqueda en profundidad",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["backtracking"],
            "pregunta": "¿Qué hace backtracking en búsqueda combinatoria?",
            "A": "Explora y retrocede al detectar que la parcial no puede llevar a solución",
            "B": "Ordena con merge sort",
            "C": "Calcula autovalores",
            "D": "Entrena una red neuronal",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
    ],
    "Anàlisi Complexa i de Fourier": [
        {
            "etiquetas": ["serie fourier"],
            "pregunta": "¿Qué representa una serie de Fourier de una función periódica?",
            "A": "Suma de sinusoides armónicas de frecuencias múltiplos de la fundamental",
            "B": "Solo el valor medio sin armónicos",
            "C": "La integral de línea en el plano complejo",
            "D": "Un polinomio de Taylor finito siempre",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["residuo"],
            "pregunta": "En el teorema de los residuos, los residuos se usan para:",
            "A": "Calcular integrales de contorno en el plano complejo",
            "B": "Diagonalizar matrices reales",
            "C": "Resolver sistemas lineales por Gauss",
            "D": "Medir entropía de Shannon",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
    ],
    "Anàlisi de Dades Complexes": [
        {
            "etiquetas": ["bootstrap", "remuestreo"],
            "pregunta": "En análisis de datos, el bootstrap sirve para:",
            "A": "Estimar la incertidumbre de un estadístico remuestreando datos",
            "B": "Garantizar R²=1",
            "C": "Eliminar multicolinealidad siempre",
            "D": "Compilar SQL",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["devianza"],
            "pregunta": "En modelos GLM, la devianza mide:",
            "A": "Bondad de ajuste relativa al modelo saturado",
            "B": "La velocidad de la luz",
            "C": "El número de clusters k-means",
            "D": "La profundidad de un árbol binario",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
    ],
    "Intel·ligència Artificial": [
        {
            "etiquetas": ["heurística admisible"],
            "pregunta": "En A*, una heurística h es admisible si:",
            "A": "No sobreestima el coste real óptimo hasta la meta",
            "B": "Siempre devuelve cero",
            "C": "Solo aplica a POO",
            "D": "Requiere grafo no dirigido",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["gramática"],
            "pregunta": "En IA simbólica, una gramática formal define:",
            "A": "Reglas que generan o analizan cadenas de un lenguaje",
            "B": "La temperatura de un gas ideal",
            "C": "El campo eléctrico en un punto",
            "D": "La entropía de un canal",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Mètodes Numèrics i Probabilístics": [
        {
            "etiquetas": ["método multipaso", "multipaso"],
            "pregunta": "Un método multipaso para EDO usa:",
            "A": "Varios valores anteriores de la solución para avanzar",
            "B": "Solo la condición inicial sin iterar",
            "C": "Solo integración por partes simbólica",
            "D": "Un join SQL entre tablas",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["pseudoaleatorio", "monte carlo"],
            "pregunta": "En Monte Carlo, los números pseudoaleatorios sirven para:",
            "A": "Simular incertidumbre y estimar integrales o esperanzas",
            "B": "Garantizar resultados exactos siempre",
            "C": "Resolver sistemas lineales por Jacobi",
            "D": "Demostrar teoremas de álgebra lineal",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["runge-kutta", "rk4"],
            "pregunta": "El método RK4 para EDO es de orden local:",
            "A": "4",
            "B": "1",
            "C": "0",
            "D": "2",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Optimització": [
        {
            "etiquetas": ["bfgs"],
            "pregunta": "BFGS es un método típico para:",
            "A": "Optimización no lineal sin restricciones (cuasi-Newton)",
            "B": "Resolver EDP hiperbólicas",
            "C": "Entrenar redes convolucionales",
            "D": "Indexar bases NoSQL",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["variables de decisión"],
            "pregunta": "En programación lineal, las variables de decisión son:",
            "A": "Las incógnitas que el modelo puede elegir",
            "B": "Solo parámetros aleatorios observados",
            "C": "Los autovalores de la matriz",
            "D": "Las etiquetas de clase",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
    ],
    "Aprenentatge Computacional": [
        {
            "etiquetas": ["aprendizaje supervisado"],
            "pregunta": "¿Qué caracteriza el aprendizaje supervisado?",
            "A": "Hay etiquetas de salida conocidas en entrenamiento",
            "B": "No hay variables de entrada",
            "C": "Solo clustering sin métricas",
            "D": "No se define función de pérdida",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["regularización"],
            "pregunta": "¿Para qué sirve la regularización L2 en un modelo lineal?",
            "A": "Penalizar magnitudes grandes de pesos para reducir sobreajuste",
            "B": "Aumentar siempre el número de capas ocultas",
            "C": "Eliminar el conjunto de validación",
            "D": "Calcular la entropía de Shannon",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Computació i Simulació d'Altes Prestacions": [
        {
            "etiquetas": ["escalabilidad fuerte"],
            "pregunta": "La escalabilidad fuerte mide el rendimiento cuando:",
            "A": "El tamaño del problema se mantiene fijo al aumentar procesadores",
            "B": "Solo crece la red IoT",
            "C": "No hay comunicación MPI",
            "D": "El speedup es siempre lineal sin límite",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["cuello de botella"],
            "pregunta": "En paralelismo, un cuello de botella es:",
            "A": "Un componente que limita el rendimiento global del sistema",
            "B": "Un tipo de base de datos NoSQL",
            "C": "Una función de activación ReLU",
            "D": "Un protocolo HTTP",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
    ],
    "Equacions en Derivades Parcials": [
        {
            "etiquetas": ["formulación débil"],
            "pregunta": "En formulación débil de una EDP, la solución se busca en:",
            "A": "Un espacio de funciones Sobolev (p. ej. H¹₀)",
            "B": "Solo números enteros",
            "C": "El espacio de matrices ortogonales",
            "D": "Un árbol de sintaxis",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["discriminante", "elíptica"],
            "pregunta": "Si B²−4AC<0 en un punto, la EDP de 2º orden en ese punto es:",
            "A": "Elíptica",
            "B": "Hiperbólica",
            "C": "Parabólica",
            "D": "Algebraica",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Calculo",
        },
    ],
    "Física, Abstracció i Computació": [
        {
            "etiquetas": ["primera ley", "inercia"],
            "pregunta": "¿Qué enuncia la primera ley de Newton (inercia)?",
            "A": "Un cuerpo permanece en su estado de movimiento si la fuerza neta es cero",
            "B": "F = m·a siempre",
            "C": "A toda acción hay reacción igual y opuesta",
            "D": "La luz se refleja con ángulo 90° siempre",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["refracción", "snell"],
            "pregunta": "La ley de Snell para refracción relaciona:",
            "A": "n₁ sin θ₁ = n₂ sin θ₂",
            "B": "V = I·R",
            "C": "p = m·v",
            "D": "F = G m₁ m₂ / r²",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["campo magnético"],
            "pregunta": "¿Qué es el campo magnético B?",
            "A": "Campo vectorial que ejerce fuerza sobre cargas en movimiento",
            "B": "Energía potencial por unidad de masa",
            "C": "La frecuencia de una onda sonora",
            "D": "La presión de un gas ideal",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["potencia eléctrica"],
            "pregunta": "En corriente continua, la potencia disipada en una resistencia es:",
            "A": "P = V·I = I²·R",
            "B": "P = m·g·h siempre",
            "C": "P = λ·f",
            "D": "P = F·v solo en óptica",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Calculo",
        },
    ],
    "Teoria de la Informació": [
        {
            "etiquetas": ["información mutua", "mutua"],
            "pregunta": "¿Qué es la información mutua I(X;Y)?",
            "A": "Entropía conjunta",
            "B": "Entropía condicional",
            "C": "Capacidad del canal",
            "D": "Reducción de entropía de X al conocer Y",
            "correcta": "D",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["entropía conjunta", "H(X,Y)"],
            "pregunta": "¿Qué mide la entropía conjunta H(X,Y)?",
            "A": "Solo la entropía marginal H(X)",
            "B": "Incertidumbre conjunta de X e Y",
            "C": "La capacidad de un canal con ruido",
            "D": "La latencia de transmisión",
            "correcta": "B",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["capacidad canal"],
            "pregunta": "La capacidad de canal C es:",
            "A": "La tasa máxima fiable de información transmisible",
            "B": "La entropía de la fuente únicamente",
            "C": "El tamaño de RAM",
            "D": "La latencia de red",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["codificación fuente"],
            "pregunta": "La codificación de fuente en Shannon busca:",
            "A": "Representar símbolos con menos bits usando probabilidades",
            "B": "Cifrar con clave pública RSA",
            "C": "Entrenar una CNN",
            "D": "Resolver una EDP elíptica",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
    ],
    "Bases de Dades No Relacionals": [
        {
            "etiquetas": ["neo4j", "grafo"],
            "pregunta": "¿Qué es Neo4j?",
            "A": "Base de datos de grafos (nodos y relaciones)",
            "B": "Motor documental BSON",
            "C": "Sistema relacional con SQL",
            "D": "Almacén solo clave-valor",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["cypher", "MATCH"],
            "pregunta": "En Cypher, ¿qué describe el patrón (a)-[r]->(b)?",
            "A": "Una relación dirigida de a hacia b",
            "B": "Un documento BSON en MongoDB",
            "C": "Un JOIN SQL entre tablas",
            "D": "Un índice hash en disco",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["mongodb", "$project"],
            "pregunta": "¿Para qué sirve el operador $project en MongoDB?",
            "A": "Seleccionar o renombrar campos en la salida",
            "B": "Crear nodos en Neo4j",
            "C": "Ejecutar Cypher MATCH",
            "D": "Definir claves foráneas SQL",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["CAP", "teorema CAP"],
            "pregunta": "El teorema CAP en sistemas distribuidos afirma que solo puedes garantizar simultáneamente:",
            "A": "Las tres: consistencia, disponibilidad y tolerancia a particiones",
            "B": "Dos de las tres propiedades (C, A, P) a la vez",
            "C": "Solo consistencia sin disponibilidad",
            "D": "Solo SQL y ACID",
            "correcta": "B",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["$group", "agregación"],
            "pregunta": "¿Qué hace el operador $group en una pipeline de MongoDB?",
            "A": "Ordena por un campo",
            "B": "Agrupa documentos y aplica acumuladores",
            "C": "Proyecta solo algunos campos",
            "D": "Ejecuta un JOIN relacional",
            "correcta": "B",
            "dificultad": "Media",
            "tipo": "Calculo",
        },
    ],
    "Informació Quàntica": [
        {
            "etiquetas": ["puerta cuántica", "puerta cuantica"],
            "pregunta": "Una puerta cuántica es:",
            "A": "Operación unitaria reversible sobre qubits",
            "B": "Un firewall clásico",
            "C": "Un índice hash en disco",
            "D": "Un método de bisección",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["estado de bell", "bell"],
            "pregunta": "Un estado de Bell es:",
            "A": "Un estado entrelazado de dos qubits",
            "B": "Un bit clásico de paridad",
            "C": "Un protocolo HTTP",
            "D": "Un índice secundario SQL",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["qubit"],
            "pregunta": "¿Qué es un qubit?",
            "A": "Bit cuántico en superposición de |0⟩ y |1⟩",
            "B": "Un byte clásico de 8 bits",
            "C": "Un protocolo TCP",
            "D": "Un índice SQL",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["cnot"],
            "pregunta": "La puerta CNOT es:",
            "A": "Control-NOT de dos qubits (entrelaza en circuitos)",
            "B": "Una FFT clásica",
            "C": "Un join SQL",
            "D": "Un método de bisección",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Modelització i Simulació": [
        {
            "etiquetas": ["euler", "discretización"],
            "pregunta": "Discretizar y'=f(t,y) con Euler explícito (paso h) produce:",
            "A": "y_{n+1}=y_n-h f(t_n,y_n)",
            "B": "y_{n+1}=y_n",
            "C": "y_{n+1}=f(y_n) sin h",
            "D": "y_{n+1}=y_n+h f(t_n,y_n)",
            "correcta": "D",
            "dificultad": "Dificil",
            "tipo": "Calculo",
        },
        {
            "etiquetas": ["bifurcació", "punt fix"],
            "pregunta": "f(x)=r·x−x³: puntos fijos reales además de x=0 existen cuando:",
            "A": "r≤1",
            "B": "r>1",
            "C": "r=0",
            "D": "nunca",
            "correcta": "B",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
    ],
    "Sistemes Distribuïts i el Núvol": [
        {
            "etiquetas": ["vpc", "aws"],
            "pregunta": "Una VPC de AWS es:",
            "A": "Un tipo de instancia EC2",
            "B": "Un bucket S3",
            "C": "Una red virtual aislada lógicamente en la nube",
            "D": "Un pod de Kubernetes",
            "correcta": "C",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["kubernetes", "pod"],
            "pregunta": "¿Qué es un pod en Kubernetes?",
            "A": "Nodo físico del clúster",
            "B": "Unidad mínima desplegable (uno o más contenedores)",
            "C": "Un bucket S3",
            "D": "Un Internet Gateway",
            "correcta": "B",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["lambda", "serverless"],
            "pregunta": "AWS Lambda se describe habitualmente como compute:",
            "A": "Serverless (ejecución bajo demanda sin gestionar servidores)",
            "B": "Solo almacenamiento de objetos",
            "C": "Base de datos relacional obligatoria",
            "D": "VPN site-to-site únicamente",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Xarxes Neuronals i Aprenentatge Profund": [
        {
            "etiquetas": ["lstm"],
            "pregunta": "¿Para qué se usa típicamente una LSTM?",
            "A": "Secuencias con memoria a largo plazo (series temporales, texto)",
            "B": "Solo clustering k-means",
            "C": "Integración numérica de EDO",
            "D": "Consultas SQL JOIN",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["transformer"],
            "pregunta": "Los modelos Transformer se basan principalmente en:",
            "A": "Mecanismos de atención (self-attention)",
            "B": "Solo convoluciones 2D de imágenes sin atención",
            "C": "Árboles de decisión voraces",
            "D": "Método de bisección",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
    ],
    "Anàlisi de Dades Financeres": [
        {
            "etiquetas": ["covered call", "opciones"],
            "pregunta": "Un covered call combina principalmente:",
            "A": "Posición larga en el subyacente y venta de una call",
            "B": "Solo compra de puts sin activo",
            "C": "Dos swaps de tipos de interés",
            "D": "Una operación de arbitraje cuántico",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["arbol binomial", "opciones"],
            "pregunta": "En un árbol binomial de opciones, el precio justo se obtiene típicamente:",
            "A": "Descuento risk-neutral de payoffs en los nodos finales",
            "B": "Solo con la media del PIB",
            "C": "Con el coeficiente Gini",
            "D": "Con el multiplicador keynesiano",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["tvar", "cvar", "var"],
            "pregunta": "El Expected Shortfall (CVaR) respecto al VaR clásico:",
            "A": "Promedia las pérdidas en la cola más allá del umbral de VaR",
            "B": "Ignora las pérdidas extremas",
            "C": "Solo usa datos del último mes",
            "D": "Es igual al precio de cierre",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["ratio sortino"],
            "pregunta": "El ratio de Sortino penaliza principalmente:",
            "A": "La volatilidad a la baja (riesgo de pérdidas)",
            "B": "Solo la inflación esperada",
            "C": "El número de qubits",
            "D": "La entropía de Shannon",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["ratio sharpe"],
            "pregunta": "El ratio de Sharpe mide:",
            "A": "Exceso de rentabilidad por unidad de riesgo (volatilidad)",
            "B": "Solo el PIB nominal",
            "C": "La entropía de un mensaje",
            "D": "El número de aristas de un grafo",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Anàlisi de Dades Temporals": [
        {
            "etiquetas": ["garch", "volatilidad"],
            "pregunta": "Un modelo GARCH(1,1) modela principalmente:",
            "A": "La volatilidad condicional que cambia en el tiempo",
            "B": "Solo la media constante del PIB",
            "C": "El payoff de una opción call",
            "D": "La beta de un activo en CAPM",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["sarima", "estacional"],
            "pregunta": "SARIMA extiende ARIMA incorporando:",
            "A": "Componentes estacionales (periodo estacional s)",
            "B": "Solo redes neuronales convolucionales",
            "C": "Solo integración por partes",
            "D": "Cifrado cuántico obligatorio",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["arima", "sarima"],
            "pregunta": "Un modelo ARIMA(p,d,q) es para:",
            "A": "Series temporales con componentes autorregresivos e integrados",
            "B": "Solo imágenes RGB",
            "C": "EDP hiperbólicas",
            "D": "Cifrado cuántico",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Anàlisi Topològica de Dades": [
        {
            "etiquetas": ["0-símplice", "0-simplice"],
            "pregunta": "En un complejo simplicial, un 0-símplice es:",
            "A": "Un vértice (punto)",
            "B": "Una cara triangular",
            "C": "Un tetraedro",
            "D": "Una arista únicamente",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["persistencia", "diagrama persistencia"],
            "pregunta": "Un diagrama de persistencia en TDA muestra:",
            "A": "Nacimiento y muerte de características topológicas al variar escala",
            "B": "Solo la media de una serie",
            "C": "La tabla de verdad de un circuito",
            "D": "El plan de ejecución SQL",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["1-símplice", "1-simplice", "arista"],
            "pregunta": "En un complejo simplicial, un 1-símplice representa:",
            "A": "Una arista entre dos vértices",
            "B": "Un volumen tetraédrico",
            "C": "Una componente conexa aislada",
            "D": "Un histograma de luminosidad",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Calculo",
        },
    ],
    "Internet de les Coses": [
        {
            "etiquetas": ["sensor", "iot"],
            "pregunta": "¿Qué es un sensor en IoT?",
            "A": "Dispositivo que captura datos del entorno",
            "B": "Actuador que solo ejecuta acciones",
            "C": "Base de datos en la nube",
            "D": "Protocolo HTTP",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["coap", "actuador"],
            "pregunta": "En IoT, un actuador es un dispositivo que:",
            "A": "Ejecuta una acción física a partir de una señal (motor, relé, etc.)",
            "B": "Solo mide temperatura sin actuar",
            "C": "Solo cifra tráfico HTTPS",
            "D": "Calcula autovalores",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["mqtt"],
            "pregunta": "MQTT en IoT es principalmente:",
            "A": "Protocolo de mensajería ligero publicar/suscribir",
            "B": "Un método de integración de Fourier",
            "C": "Un tipo de join SQL",
            "D": "Un algoritmo de Dijkstra",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
    ],
    "Mètodes d Anàlisi en Ciències de la Salut": [
        {
            "etiquetas": ["ic 95", "intervalo confianza"],
            "pregunta": "Un IC del 95% para una proporción en salud:",
            "A": "Intervalo estimado con método del 95% para el parámetro",
            "B": "Probabilidad 95% de curar siempre",
            "C": "El número de pacientes del estudio",
            "D": "La mediana sin dispersión",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["sensibilidad", "especificidad"],
            "pregunta": "La sensibilidad de un test diagnóstico es:",
            "A": "P(test+|enfermo) — detectar verdaderos positivos",
            "B": "P(sano|test+)",
            "C": "La media de la muestra",
            "D": "El coeficiente de una regresión",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["odds ratio"],
            "pregunta": "El odds ratio (OR) en salud compara:",
            "A": "La odds de un desenlace entre dos grupos",
            "B": "La velocidad de la luz",
            "C": "El número de qubits",
            "D": "La integral de una EDO",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Anàlisi de Dades en Astrofísica": [
        {
            "etiquetas": ["matched filter", "SNR", "ligo"],
            "pregunta": "En detección de ondas gravitacionales, ¿qué mide el filtro adaptado (matched filter)?",
            "A": "Correlación óptima señal/ruido (SNR)",
            "B": "Paralaje de una galaxia",
            "C": "Temperatura de un cuerpo negro",
            "D": "Número de codones en ADN",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["neutrino", "supernova"],
            "pregunta": "En modelos de supernova, un conjunto de datos de neutrinos simulados sirve para:",
            "A": "Estudiar distribuciones de neutrinos esperados",
            "B": "Curvas de luz en rayos gamma VHE",
            "C": "Espectros de radiación de cuerpo negro",
            "D": "Matrices de distancia de edición",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Bioinformàtica": [
        {
            "etiquetas": ["k-mer", "kmer"],
            "pregunta": "Un k-mer en una secuencia biológica es:",
            "A": "Una subcadena contigua de longitud k",
            "B": "Un aminoácido modificado",
            "C": "Un tipo de base de datos relacional",
            "D": "Un protocolo MQTT",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["codón"],
            "pregunta": "Un codón en ADN codifica típicamente:",
            "A": "Un aminoácido (o señal de inicio/stop)",
            "B": "Un fotón",
            "C": "Un autovalor",
            "D": "Un índice B-tree",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["alineamiento"],
            "pregunta": "Un alineamiento global de secuencias (p. ej. Needleman-Wunsch) busca:",
            "A": "La correspondencia óptima entre dos secuencias completas",
            "B": "La raíz de una EDP",
            "C": "El speedup de Amdahl",
            "D": "La capacidad de canal",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["transcripcion", "traduccion"],
            "pregunta": "¿Qué proceso convierte ADN en ARNm?",
            "A": "Traducción",
            "B": "Replicación",
            "C": "Transducción",
            "D": "Transcripción",
            "correcta": "D",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["levenshtein", "edicion"],
            "pregunta": "La distancia de edición (Levenshtein) entre dos cadenas mide:",
            "A": "Coste mínimo de inserciones, borrados y sustituciones",
            "B": "Solo sustituciones en posiciones alineadas",
            "C": "El número de codones stop",
            "D": "La temperatura de melting del ADN",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Informació i Seguretat": [
        {
            "etiquetas": ["AES", "SubBytes"],
            "pregunta": "En AES, ¿qué paso aplica la tabla S-box a cada byte del estado?",
            "A": "SubBytes",
            "B": "ShiftRows",
            "C": "MixColumns",
            "D": "AddRoundKey",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["LFSR"],
            "pregunta": "En un LFSR, el bit de salida y el desplazamiento dependen de:",
            "A": "XOR de bits del estado según el polinomio de retroalimentación",
            "B": "La tríada CIA",
            "C": "El principio de mínimo privilegio",
            "D": "Ocultar información en otro medio",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["salt", "sal"],
            "pregunta": "En contraseñas almacenadas, un salt sirve para:",
            "A": "Hacer único el hash y dificultar tablas arcoíris",
            "B": "Comprimir el mensaje cifrado",
            "C": "Aumentar el ancho de banda de red",
            "D": "Calcular la integral de Fourier",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["hash", "función hash"],
            "pregunta": "Una función hash criptográfica debe ser:",
            "A": "Difícil de invertir y sensible a cambios (resumen fijo)",
            "B": "Reversible con la misma clave simétrica",
            "C": "Lineal en el tamaño del mensaje siempre",
            "D": "Igual a un cifrado RSA",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["cifrado", "criptografía"],
            "pregunta": "El cifrado simétrico usa:",
            "A": "La misma clave secreta para cifrar y descifrar",
            "B": "Solo claves públicas distintas",
            "C": "Sin claves",
            "D": "Solo hash sin mensaje",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["disponibilidad cia"],
            "pregunta": "En la tríada CIA, la disponibilidad garantiza que:",
            "A": "Los servicios y datos estén accesibles cuando se necesiten",
            "B": "Nadie pueda leer el mensaje en tránsito",
            "C": "El mensaje no pueda alterarse sin detección",
            "D": "La clave pública sea matemáticamente irreversible",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["kerckhoffs"],
            "pregunta": "El principio de Kerckhoffs establece que la seguridad debe residir en:",
            "A": "La clave secreta, no en el algoritmo",
            "B": "Ocultar el algoritmo de cifrado",
            "C": "La longitud del mensaje en claro",
            "D": "El hash del certificado X.509",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["vigenere", "hill"],
            "pregunta": "Vigenère y Hill son ejemplos de:",
            "A": "Cifrados clásicos por sustitución/transformación lineal",
            "B": "Protocolos de routing IP",
            "C": "Funciones hash SHA-3",
            "D": "Filtros de Bloom",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["euler", "modular"],
            "pregunta": "Si gcd(a,m)=1, el inverso modular de a módulo m existe porque:",
            "A": "a y m son coprimos (φ(m) cuenta unidades)",
            "B": "m es siempre primo par",
            "C": "a debe ser 0",
            "D": "No hace falta gcd",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
    ],
    "Teoria de Jocs": [
        {
            "etiquetas": ["estrategia dominante"],
            "pregunta": "Una estrategia dominante para un jugador es aquella que:",
            "A": "Le da pago mayor independientemente de lo que juegue el rival",
            "B": "Solo es óptima si el rival coopera",
            "C": "Requiere comunicación previa obligatoria",
            "D": "Minimiza siempre el pago del rival",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["juego repetido", "spe"],
            "pregunta": "En un juego repetido, un equilibrio perfecto en subjuegos (SPE) exige:",
            "A": "Ser equilibrio de Nash en cada subjuego alcanzado",
            "B": "Que todos los pagos sean iguales",
            "C": "Que no haya estrategias mixtas",
            "D": "Que el grafo sea bipartito",
            "correcta": "A",
            "dificultad": "Dificil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["equilibrio de nash"],
            "pregunta": "Un equilibrio de Nash en estrategias puras es un perfil donde:",
            "A": "Ningún jugador mejora desviándose unilateralmente",
            "B": "Todos cooperan siempre",
            "C": "La suma de pagos es cero necesariamente",
            "D": "El grafo es acíclico",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
    ],
    "Visió per Computador": [
        {
            "etiquetas": ["pixel"],
            "pregunta": "¿Qué es un píxel en una imagen digital?",
            "A": "El elemento mínimo con valor de intensidad o color",
            "B": "Un filtro de convolución 3×3",
            "C": "El canal alfa de RGBA",
            "D": "La función de pérdida de la red",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["histograma"],
            "pregunta": "Un histograma de intensidad con 256 bins agrupa:",
            "A": "Cuántos píxeles caen en cada nivel de gris (0–255)",
            "B": "El número de capas de una CNN",
            "C": "La IoU entre dos detecciones",
            "D": "El stride de la última convolución",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Calculo",
        },
        {
            "etiquetas": ["tensor", "rgb"],
            "pregunta": "En visión, una imagen RGB suele representarse como tensor:",
            "A": "Alto × ancho × 3 canales de color",
            "B": "Solo un escalar por píxel sin canales",
            "C": "Una matriz de autovalores",
            "D": "Un árbol de sintaxis",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["stride", "padding"],
            "pregunta": "En una convolución 2D con padding, el padding sirve para:",
            "A": "Controlar el tamaño espacial de salida y tratar bordes",
            "B": "Eliminar canales de color",
            "C": "Calcular la entropía de Shannon",
            "D": "Resolver una EDO elíptica",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["convolución", "convolution"],
            "pregunta": "En visión, una convolución 2D con un kernel:",
            "A": "Aplica un filtro local deslizante sobre la imagen",
            "B": "Ordena píxeles por brillo global sin vecindad",
            "C": "Resuelve una EDO parabólica",
            "D": "Ejecuta un JOIN SQL",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["pooling"],
            "pregunta": "El max pooling en CNN suele servir para:",
            "A": "Reducir resolución espacial y dar invarianza local",
            "B": "Aumentar el número de canales siempre",
            "C": "Calcular la derivada de una función",
            "D": "Cifrar imágenes",
            "correcta": "A",
            "dificultad": "Media",
            "tipo": "Teoria",
        },
        {
            "etiquetas": ["bounding box", "detección objetos"],
            "pregunta": "En detección de objetos, una bounding box define:",
            "A": "Un rectángulo que localiza un objeto en la imagen",
            "B": "La entropía del canal verde",
            "C": "El autovalor máximo de una matriz",
            "D": "Un join entre dos tablas SQL",
            "correcta": "A",
            "dificultad": "Facil",
            "tipo": "Calculo",
        },
    ],
}
